GraphicsQualityLevels = {
	[1] = { VideoOptionsEffectsPanelViewDistance = 177,		--LOW mode
			VideoOptionsEffectsPanelTerrainDetail = 0,
			VideoOptionsEffectsPanelParticleDensity = 0.1, 
			VideoOptionsEffectsPanelEnvironmentDetail = 0.5,
			VideoOptionsEffectsPanelClutterDensity = 16,
			VideoOptionsEffectsPanelClutterRadius = 70,
			VideoOptionsEffectsPanelShadowQuality = 0, 
			VideoOptionsEffectsPanelTextureResolution = 0,
			VideoOptionsEffectsPanelTextureFiltering = 0,
			VideoOptionsEffectsPanelWeatherIntensity = 0,
			VideoOptionsEffectsPanelPlayerTexture = 8,					
			VideoOptionsEffectsPanelLiquidDetail = 0,
			VideoOptionsEffectsPanelSunshafts = false,
			VideoOptionsEffectsPanelFullScreenGlow = false,
			VideoOptionsEffectsPanelDeathEffect = false,
			VideoOptionsEffectsPanelProjectedTextures = false,
			},
	[2] = { VideoOptionsEffectsPanelViewDistance = 507,		--FAIR mode
			VideoOptionsEffectsPanelTerrainDetail = 0,
			VideoOptionsEffectsPanelParticleDensity = 0.4, 
			VideoOptionsEffectsPanelEnvironmentDetail = 0.75,
			VideoOptionsEffectsPanelClutterDensity = 40,
			VideoOptionsEffectsPanelClutterRadius = 110,
			VideoOptionsEffectsPanelShadowQuality = 0,			
			VideoOptionsEffectsPanelTextureResolution = 0,
			VideoOptionsEffectsPanelTextureFiltering = 1,
			VideoOptionsEffectsPanelWeatherIntensity = 0,
			VideoOptionsEffectsPanelPlayerTexture = 8,					
			VideoOptionsEffectsPanelLiquidDetail = 1,
			VideoOptionsEffectsPanelSunshafts = false,
			VideoOptionsEffectsPanelFullScreenGlow = true,
			VideoOptionsEffectsPanelDeathEffect = true,
			VideoOptionsEffectsPanelProjectedTextures = false,
			},
	[3] = { VideoOptionsEffectsPanelViewDistance = 727,		--GOOD mode
			VideoOptionsEffectsPanelTerrainDetail = 0,
			VideoOptionsEffectsPanelParticleDensity = 0.6, 
			VideoOptionsEffectsPanelEnvironmentDetail = 1.0,
			VideoOptionsEffectsPanelClutterDensity = 64,
			VideoOptionsEffectsPanelClutterRadius = 160,
			VideoOptionsEffectsPanelShadowQuality = 1,
			VideoOptionsEffectsPanelTextureResolution = 1,
			VideoOptionsEffectsPanelTextureFiltering = 2,
			VideoOptionsEffectsPanelWeatherIntensity = 2,
			VideoOptionsEffectsPanelPlayerTexture = 9,					
			VideoOptionsEffectsPanelLiquidDetail = 2,
			VideoOptionsEffectsPanelSunshafts = false,
			VideoOptionsEffectsPanelFullScreenGlow = true,
			VideoOptionsEffectsPanelDeathEffect = true,		
			VideoOptionsEffectsPanelProjectedTextures = true,
			},
	[4] = { VideoOptionsEffectsPanelViewDistance = 1057,	--HIGH mode
			VideoOptionsEffectsPanelTerrainDetail = 1,
			VideoOptionsEffectsPanelParticleDensity = 0.8, 
			VideoOptionsEffectsPanelEnvironmentDetail = 1.25,
			VideoOptionsEffectsPanelClutterDensity = 96,
			VideoOptionsEffectsPanelClutterRadius = 220,
			VideoOptionsEffectsPanelShadowQuality = 4,
			VideoOptionsEffectsPanelTextureResolution = 1,
			VideoOptionsEffectsPanelTextureFiltering = 4,
			VideoOptionsEffectsPanelWeatherIntensity = 3,
			VideoOptionsEffectsPanelPlayerTexture = 9,					
			VideoOptionsEffectsPanelLiquidDetail = 2,
			VideoOptionsEffectsPanelSunshafts = true,
			VideoOptionsEffectsPanelFullScreenGlow = true,
			VideoOptionsEffectsPanelDeathEffect = true,
			VideoOptionsEffectsPanelProjectedTextures = true,
			},
	[5] = { VideoOptionsEffectsPanelViewDistance = 1277,	--ULTRA mode
			VideoOptionsEffectsPanelTerrainDetail = 1,
			VideoOptionsEffectsPanelParticleDensity = 1.0, 
			VideoOptionsEffectsPanelEnvironmentDetail = 1.5,
			VideoOptionsEffectsPanelClutterDensity = 128,
			VideoOptionsEffectsPanelClutterRadius = 300,
			VideoOptionsEffectsPanelShadowQuality = 5,
			VideoOptionsEffectsPanelTextureResolution = 1,
			VideoOptionsEffectsPanelTextureFiltering = 5,
			VideoOptionsEffectsPanelWeatherIntensity = 3,
			VideoOptionsEffectsPanelPlayerTexture = 9,				
			VideoOptionsEffectsPanelLiquidDetail = 3,	
			VideoOptionsEffectsPanelSunshafts = true,
			VideoOptionsEffectsPanelFullScreenGlow = true,
			VideoOptionsEffectsPanelDeathEffect = true,
			VideoOptionsEffectsPanelProjectedTextures = true,
			},
	[6] = { VideoOptionsEffectsPanelViewDistance = 0,
			VideoOptionsEffectsPanelTerrainDetail = 0,
			VideoOptionsEffectsPanelParticleDensity = 0, 
			VideoOptionsEffectsPanelEnvironmentDetail = 0,
			VideoOptionsEffectsPanelClutterDensity = 0,
			VideoOptionsEffectsPanelClutterRadius = 0,
			VideoOptionsEffectsPanelShadowQuality = 0,
			VideoOptionsEffectsPanelTextureResolution = 0,
			VideoOptionsEffectsPanelTextureFiltering = 0,
			VideoOptionsEffectsPanelWeatherIntensity = 0,
			VideoOptionsEffectsPanelPlayerTexture = 8,					
			VideoOptionsEffectsPanelLiquidDetail = 0,
			VideoOptionsEffectsPanelSunshafts = false,
			VideoOptionsEffectsPanelFullScreenGlow = false,
			VideoOptionsEffectsPanelDeathEffect = false,
			VideoOptionsEffectsPanelProjectedTextures = true,
			},			
}