-- Main Action Bar
MAIN_ACTION_BAR_DEFAULT_OFFSET_Y = 45;

-- Action Bars
ACTION_BAR_3_ANCHOR_POINT = "BOTTOM";
ACTION_BAR_3_RELATIVE_TO = "UIParent";
ACTION_BAR_3_RELATIVE_POINT = "BOTTOM";

-- Offset between main action bar and other bars
BOTTOM_ACTION_BARS_INITIAL_OFFSET_Y = 45;
-- Space between bottom action bars
BOTTOM_ACTION_BARS_SPACER_Y = 5;

-- Micro Menu
MICRO_MENU_ANCHOR_POINT = "BOTTOMRIGHT";
MICRO_MENU_ANCHOR_RELATIVE_TO = "MicroButtonAndBagsBar";
MICRO_MENU_ANCHOR_RELATIVE_POINT = "BOTTOMRIGHT";
MICRO_MENU_ANCHOR_OFFSET_X = 0;
MICRO_MENU_ANCHOR_OFFSET_Y = 0;

-- Bags Bar
BAGS_ANCHOR_POINT = "TOPRIGHT";
BAGS_ANCHOR_RELATIVE_TO = "MicroButtonAndBagsBar";
BAGS_ANCHOR_RELATIVE_POINT = "TOPRIGHT";
BAGS_ANCHOR_OFFSET_X = 0;
BAGS_ANCHOR_OFFSET_Y = 10;

-- Staus Bar
STATUS_BAR_1_ANCHOR_OFFSET_Y = 0;
STATUS_BAR_2_ANCHOR_OFFSET_Y = 17;

-- Chat Frame
CHAT_FRAME_ANCHOR_OFFSET_Y = 50;
