-- Action Bar Global Config
ACTION_BARS_SKIP_AUTOMATIC_POSITIONING = false;

-- Main Action Bar
MAIN_ACTION_BAR_POINT = "BOTTOM";
MAIN_ACTION_BAR_RELATIVE_TO = "UIParent";
MAIN_ACTION_BAR_RELATIVE_POINT = "BOTTOM";
MAIN_ACTION_BAR_OFFSET_X = 0;
MAIN_ACTION_BAR_OFFSET_Y = 45;
MAIN_ACTION_BAR_MANAGE_END_CAPS = true;

-- Action Bars
ACTION_BAR_2_ANCHOR_POINT = "BOTTOM";
ACTION_BAR_2_RELATIVE_TO = "UIParent";
ACTION_BAR_2_RELATIVE_POINT = "BOTTOM";
ACTION_BAR_2_OFFSET_X = 0; -- Overridden by UpdateBottomActionBarPositions.
ACTION_BAR_2_OFFSET_Y = 0; -- Overridden by UpdateBottomActionBarPositions.

ACTION_BAR_3_ANCHOR_POINT = "BOTTOM";
ACTION_BAR_3_RELATIVE_TO = "UIParent";
ACTION_BAR_3_RELATIVE_POINT = "BOTTOM";
ACTION_BAR_3_OFFSET_X = 0; -- Overridden by UpdateBottomActionBarPositions.
ACTION_BAR_3_OFFSET_Y = 0; -- Overridden by UpdateBottomActionBarPositions.
ACTION_BAR_3_BOTTOM_BAR_EXCLUDE_FROM_STACK_INCREMENT = false;

-- Space between bottom action bars
BOTTOM_ACTION_BARS_SPACER_Y = 5;
PRIMARY_AND_SECONDARY_STATUS_TRACKING_BAR_SPACER_Y = 5;

-- Micro Menu
MICRO_MENU_ANCHOR_POINT = "BOTTOMRIGHT";
MICRO_MENU_ANCHOR_RELATIVE_TO = "MicroButtonAndBagsBar";
MICRO_MENU_ANCHOR_RELATIVE_POINT = "BOTTOMRIGHT";
MICRO_MENU_ANCHOR_OFFSET_X = 0;
MICRO_MENU_ANCHOR_OFFSET_Y = 0;

-- Bags Bar
BAGS_ANCHOR_POINT = "TOPRIGHT";
BAGS_ANCHOR_RELATIVE_TO = "MicroButtonAndBagsBar";
BAGS_ANCHOR_RELATIVE_POINT = "TOPRIGHT";
BAGS_ANCHOR_OFFSET_X = 0;
BAGS_ANCHOR_OFFSET_Y = 10;

-- Staus Bar
STATUS_BAR_1_ANCHOR_OFFSET_X = 0;
STATUS_BAR_1_ANCHOR_RELATIVE_TO = "StatusTrackingBarManager";
STATUS_BAR_1_ANCHOR_POINT = "BOTTOM";
STATUS_BAR_1_ANCHOR_RELATIVE_POINT = "BOTTOM";
STATUS_BAR_1_ANCHOR_OFFSET_Y = 0;

STATUS_BAR_2_ANCHOR_OFFSET_X = 0;
STATUS_BAR_2_ANCHOR_RELATIVE_TO = "StatusTrackingBarManager";
STATUS_BAR_2_ANCHOR_POINT = "BOTTOM";
STATUS_BAR_2_ANCHOR_RELATIVE_POINT = "BOTTOM";
STATUS_BAR_2_ANCHOR_OFFSET_Y = 17;
STATUS_BAR_2_BOTTOM_BAR_EXCLUDE_FROM_STACK_INCREMENT = false;

-- Chat Frame
CHAT_FRAME_ANCHOR_OFFSET_Y = 50;

-- Group Finder (the "Eye")
GROUP_FINDER_ANCHOR_POINT = "BOTTOMRIGHT";
GROUP_FINDER_RELATIVE_TO = "MicroMenu";
GROUP_FINDER_RELATIVE_POINT = "BOTTOMLEFT";
GROUP_FINDER_OFFSET_X = -15;
GROUP_FINDER_OFFSET_Y = 12;
