
-- Gamepad key names.
GAMEPAD_MOD_LEFT = "SHIFT";
GAMEPAD_MOD_RIGHT = "CTRL";
GAMEPAD_MOD_LEFT_AND_RIGHT = "CTRL-SHIFT";

GAMEPAD_FACE_RIGHT = "PAD2";
GAMEPAD_FACE_BOTTOM = "PAD1";
GAMEPAD_FACE_LEFT = "PAD3";
GAMEPAD_FACE_TOP = "PAD4";

GAMEPAD_DPAD = "DIRPAD";
GAMEPAD_DPAD_HORIZONTAL = "DIRPADHORIZONTAL";
GAMEPAD_DPAD_VERTICAL = "DIRPADVERTICAL";
GAMEPAD_DPAD_RIGHT = "PADDRIGHT";
GAMEPAD_DPAD_BOTTOM = "PADDDOWN";
GAMEPAD_DPAD_LEFT = "PADDLEFT";
GAMEPAD_DPAD_TOP = "PADDUP";

GAMEPAD_SHOULDER_LEFT = "PADLSHOULDER";
GAMEPAD_SHOULDER_RIGHT = "PADRSHOULDER";
GAMEPAD_TRIGGER_LEFT = "PADLTRIGGER";
GAMEPAD_TRIGGER_RIGHT = "PADRTRIGGER";

-- "AXIS" keywords are custom and do not map to system bindings. Stick input is handled by InputAxisBinding.lua.
GAMEPAD_STICK_LEFT = "PADLSTICKAXIS";
GAMEPAD_STICK_RIGHT = "PADRSTICKAXIS";

GAMEPAD_STICK_LEFT_PRESS = "PADLSTICK";
GAMEPAD_STICK_RIGHT_PRESS = "PADRSTICK";

GAMEPAD_STICK_RIGHT_VERTICAL = "<right-stick-vertical>";
GAMEPAD_STICK_RIGHT_HORIZONTAL = "<right-stick-horizontal>";

GAMEPAD_MENU_LEFT = "PADBACK";
GAMEPAD_MENU_RIGHT = "PADFORWARD";
GAMEPAD_MENU_CENTER = "CENTERBUTTON";
GAMEPAD_MENU_SOCIAL = "PADSOCIAL";

-- Gamepad input legend keywords.
GAMEPAD_PROMPT_DIVIDER_SLASH = "SLASH";
GAMEPAD_PROMPT_DIVIDER_PLUS = "PLUS";

-- Helpers for custom input binding declarations.
GAMEPAD_BUTTON_ANY_DOWN = {"AnyDown"};
GAMEPAD_BUTTON_ANY_UP = {"AnyUp"};
GAMEPAD_BUTTON_ANY_DOWN_OR_UP = {"AnyDown", "AnyUp"};
GAMEPAD_BINDS_ALWAYS_ON_TOP = true;
