BLIZZARD_COLLECTIONS_MOUNT_JOURNAL_SHOW_FAVORITES = false;
BLIZZARD_COLLECTIONS_PETS_SHOW_SUMMON_RANDOM = true;

BLIZZARD_COLLECTIONS_TAB_STYLE_BOTTOM = "BOTTOM";
BLIZZARD_COLLECTIONS_TAB_STYLE_SIDE = "SIDE";
BLIZZARD_COLLECTIONS_TAB_STYLE = BLIZZARD_COLLECTIONS_TAB_STYLE_BOTTOM;

BLIZZARD_COLLECTIONS_COUNT_DISPLAY_STYLE_LEFT = "LEFT";
BLIZZARD_COLLECTIONS_COUNT_DISPLAY_STYLE_CENTER = "CENTER";
BLIZZARD_COLLECTIONS_COUNT_DISPLAY_STYLE = BLIZZARD_COLLECTIONS_COUNT_DISPLAY_STYLE_LEFT;
