GraphicsQualityLevels = {
	[1] = { VideoOptionsEffectsPanelViewDistance = 177,
			VideoOptionsEffectsPanelTerrainDetail = 0,
			VideoOptionsEffectsPanelSpellDetail = 0, 
			VideoOptionsEffectsPanelEnvironmentDetail = 0.5,
			VideoOptionsEffectsPanelClutterDensity = 16,
			VideoOptionsEffectsPanelClutterRadius = 70,
			VideoOptionsEffectsPanelShadowQuality = 0, 
			VideoOptionsEffectsPanelTextureResolution = 0,
			VideoOptionsEffectsPanelTextureFiltering = 0,
			VideoOptionsEffectsPanelWeatherIntensity = 0,
			VideoOptionsEffectsPanelSpecularLighting = false,
			VideoOptionsEffectsPanelFullScreenGlow = false,
			VideoOptionsEffectsPanelDeathEffect = false,			
			},
	[2] = { VideoOptionsEffectsPanelViewDistance = 507,
			VideoOptionsEffectsPanelTerrainDetail = 0,
			VideoOptionsEffectsPanelSpellDetail = 6, 
			VideoOptionsEffectsPanelEnvironmentDetail = 0.75,
			VideoOptionsEffectsPanelClutterDensity = 24,
			VideoOptionsEffectsPanelClutterRadius = 70,
			VideoOptionsEffectsPanelShadowQuality = 1,			
			VideoOptionsEffectsPanelTextureResolution = 0,
			VideoOptionsEffectsPanelTextureFiltering = 1,
			VideoOptionsEffectsPanelWeatherIntensity = 1,
			VideoOptionsEffectsPanelSpecularLighting = true,
			VideoOptionsEffectsPanelFullScreenGlow = true,
			VideoOptionsEffectsPanelDeathEffect = true,
			},
	[3] = { VideoOptionsEffectsPanelViewDistance = 727,
			VideoOptionsEffectsPanelTerrainDetail = 1,
			VideoOptionsEffectsPanelSpellDetail = 8, 
			VideoOptionsEffectsPanelEnvironmentDetail = 1.0,
			VideoOptionsEffectsPanelClutterDensity = 48,
			VideoOptionsEffectsPanelClutterRadius = 120,
			VideoOptionsEffectsPanelShadowQuality = 3,
			VideoOptionsEffectsPanelTextureResolution = 1,
			VideoOptionsEffectsPanelTextureFiltering = 3,
			VideoOptionsEffectsPanelWeatherIntensity = 2,
			VideoOptionsEffectsPanelSpecularLighting = true,
			VideoOptionsEffectsPanelFullScreenGlow = true,
			VideoOptionsEffectsPanelDeathEffect = true,			
			},
	[4] = { VideoOptionsEffectsPanelViewDistance = 1277,
			VideoOptionsEffectsPanelTerrainDetail = 1,
			VideoOptionsEffectsPanelSpellDetail = 9, 
			VideoOptionsEffectsPanelEnvironmentDetail = 1.5,
			VideoOptionsEffectsPanelClutterDensity = 64,
			VideoOptionsEffectsPanelClutterRadius = 140,
			VideoOptionsEffectsPanelShadowQuality = 4,
			VideoOptionsEffectsPanelTextureResolution = 1,
			VideoOptionsEffectsPanelTextureFiltering = 5,
			VideoOptionsEffectsPanelWeatherIntensity = 3,
			VideoOptionsEffectsPanelSpecularLighting = true,
			VideoOptionsEffectsPanelFullScreenGlow = true,
			VideoOptionsEffectsPanelDeathEffect = true,			
			},
	[5] = { VideoOptionsEffectsPanelViewDistance = 0,
			VideoOptionsEffectsPanelTerrainDetail = 0,
			VideoOptionsEffectsPanelSpellDetail = 0, 
			VideoOptionsEffectsPanelEnvironmentDetail = 0,
			VideoOptionsEffectsPanelClutterDensity = 0,
			VideoOptionsEffectsPanelClutterRadius = 0,
			VideoOptionsEffectsPanelShadowQuality = 0,
			VideoOptionsEffectsPanelTextureResolution = 0,
			VideoOptionsEffectsPanelTextureFiltering = 0,
			VideoOptionsEffectsPanelWeatherIntensity = 0,
			VideoOptionsEffectsPanelSpecularLighting = false,
			VideoOptionsEffectsPanelFullScreenGlow = false,
			VideoOptionsEffectsPanelDeathEffect = false,					
			},			
}