--REMOVE ME EVENTUALLY
LFGLIST_NAME = "Premade Groups"
FIND_A_GROUP = "Find a Group"
START_A_GROUP = "Start a Group"
LFG_LIST_SELECT_A_CATEGORY = "Make a selection.";
LFG_LIST_ENTER_NAME = "Enter a name for the group";
LFG_LIST_ITEM_LEVEL_REQ = "Minimum Item Level";
LFG_LIST_ITEM_LEVEL_INSTR_SHORT = "Item Level";
LFG_LIST_ILVL_ABOVE_YOURS = "You can't require an item level higher than your own."
LFG_LIST_VOICE_CHAT = "Voice Chat";
LFG_LIST_VOICE_CHAT_INSTR = "Voice chat program";
LFG_LIST_ITEM_LEVEL_CURRENT = "Item Level: |cffffffff%d|r";
DESCRIPTION_OF_YOUR_GROUP = "Description of your group";
LIST_GROUP = "List Group";
REQUIREMENTS = "Requirements";
LFG_LIST_CREATING_ENTRY = "Zug zug...";
DESCRIPTION = "Description";
EDIT = "Edit";
DONE_EDITING = "Done Editing";
