local eventHandlers = {
	["ADDON_ACTION_BLOCKED"] = function(...) GameEvent.HandleActionBlocked(...) end,
	["ADVENTURE_MAP_OPEN"] = function(...) GameEvent.HandleAdventureMapOpen(...) end,
	["ALLIED_RACE_OPEN"] = function(...) GameEvent.HandleAlliedRaceOpen(...) end,
	["ANIMA_DIVERSION_OPEN"] = function(...) GameEvent.HandleAnimaDiversionOpen(...) end,
	["ARTIFACT_ENDGAME_REFUND"] = function(...) GameEvent.HandleArtifactEndgameRefund(...) end,
	["ARTIFACT_RELIC_FORGE_UPDATE"] = function(...) GameEvent.HandleArtifactRelicForgeUpdate(...) end,
	["ARTIFACT_RESPEC_PROMPT"] = function(...) GameEvent.HandleArtifactRespecPrompt(...) end,
	["ARTIFACT_UPDATE"] = function(...) GameEvent.HandleArtifactUpdate(...) end,
	["AUCTION_HOUSE_CLOSED"] = function(...) GameEvent.HandleAuctionHouseClosed(...) end,
	["AUCTION_HOUSE_DISABLED"] = function(...) GameEvent.HandleAuctionHouseDisabled(...) end,
	["AUCTION_HOUSE_SHOW"] = function(...) GameEvent.HandleAuctionHouseShow(...) end,
	["AUCTION_HOUSE_SHOW_FORMATTED_NOTIFICATION"] = function(...) GameEvent.HandleAuctionHouseNotification(...) end,
	["AUCTION_HOUSE_SHOW_NOTIFICATION"] = function(...) GameEvent.HandleAuctionHouseNotification(...) end,
	["BARBER_SHOP_CLOSE"] = function(...) GameEvent.HandleBarberShopClose(...) end,
	["CHALLENGE_MODE_COMPLETED"] = function(...) GameEvent.HandleChallengeModeCompleted(...) end,
	["CHALLENGE_MODE_KEYSTONE_RECEPTABLE_OPEN"] = function(...) GameEvent.HandleChallengeModeKeystoneReceptableOpen(...) end,
	["CONFIRM_DISENCHANT_ROLL"] = function(...) GameEvent.HandleConfirmDisenchantRoll(...) end,
	["CONFIRM_TALENT_WIPE"] = function(...) GameEvent.HandleConfirmTalentWipe(...) end,
	["CONFIRM_XP_LOSS"] = function(...) GameEvent.HandleConfirmXpLoss(...) end,
	["CONVERT_TO_BIND_TO_ACCOUNT_CONFIRM"] = function(...) GameEvent.HandleConvertToBindToAccountConfirm(...) end,
	["CORPSE_IN_INSTANCE"] = function(...) GameEvent.HandleCorpseInInstance(...) end,
	["CORPSE_IN_RANGE"] = function(...) GameEvent.HandleCorpseInRange(...) end,
	["CORPSE_OUT_OF_RANGE"] = function(...) GameEvent.HandleCorpseOutOfRange(...) end,
	["COVENANT_PREVIEW_OPEN"] = function(...) GameEvent.HandleCovenantPreviewOpen(...) end,
	["CRAFTING_HOUSE_DISABLED"] = function(...) GameEvent.HandleCraftingHouseDisabled(...) end,
	["CRAFTINGORDERS_HIDE_CUSTOMER"] = function(...) GameEvent.HandleCraftingOrdersHideCustomer(...) end,
	["CRAFTINGORDERS_SHOW_CUSTOMER"] = function(...) GameEvent.HandleCraftingOrdersShowCustomer(...) end,
	["CURRENT_SPELL_CAST_CHANGED"] = function(...) GameEvent.HandleCurrentSpellCastChanged(...) end,
	["CVAR_UPDATE"] = function(...) GameEvent.HandleCvarUpdate(...) end,
	["DAILY_RESET_INSTANCE_WELCOME"] = function(...) GameEvent.HandleDailyResetInstanceWelcome(...) end,
	["DELETE_ITEM_CONFIRM"] = function(...) GameEvent.HandleDeleteItemConfirm(...) end,
	["DISABLE_TAXI_BENCHMARK"] = function(...) GameEvent.HandleDisableTaxiBenchmark(...) end,
	["DUEL_FINISHED"] = function(...) GameEvent.HandleDuelFinished(...) end,
	["ENABLE_TAXI_BENCHMARK"] = function(...) GameEvent.HandleEnableTaxiBenchmark(...) end,
	["ENCHANT_SPELL_SELECTED"] = function(...) GameEvent.HandleEnchantSpellSelected(...) end,
	["EQUIP_BIND_CONFIRM"] = function(...) GameEvent.HandleEquipBindConfirm(...) end,
	["EQUIP_BIND_REFUNDABLE_CONFIRM"] = function(...) GameEvent.HandleEquipBindRefundableConfirm(...) end,
	["EQUIP_BIND_TRADEABLE_CONFIRM"] = function(...) GameEvent.HandleEquipBindTradeableConfirm(...) end,
	["GARRISON_MISSION_NPC_CLOSED"] = function(...) GameEvent.HandleGarrisonMissionNpcClosed(...) end,
	["GARRISON_MISSION_NPC_OPENED"] = function(...) GameEvent.HandleGarrisonMissionNpcOpened(...) end,
	["GARRISON_RECRUITMENT_NPC_OPENED"] = function(...) GameEvent.HandleGarrisonRecruitmentNpcOpened(...) end,
	["GARRISON_SHIPYARD_NPC_CLOSED"] = function(...) GameEvent.HandleGarrisonShipyardNpcClosed(...) end,
	["GARRISON_SHIPYARD_NPC_OPENED"] = function(...) GameEvent.HandleGarrisonShipyardNpcOpened(...) end,
	["GARRISON_TALENT_NPC_OPENED"] = function(...) GameEvent.HandleGarrisonTalentNpcOpened(...) end,
	["GET_ITEM_INFO_RECEIVED"] = function(...) GameEvent.HandleGetItemInfoReceived(...) end,
	["GLOBAL_MOUSE_DOWN"] = function(...) GameEvent.HandleGlobalMouseEvent(...) end,
	["GLOBAL_MOUSE_UP"] = function(...) GameEvent.HandleGlobalMouseEvent(...) end,
	["GROUP_INVITE_CONFIRMATION"] = function(...) GameEvent.HandleGroupInviteConfirmation(...) end,
	["HEIRLOOM_UPGRADE_TARGETING_CHANGED"] = function(...) GameEvent.HandleHeirloomUpgradeTargetingChanged(...) end,
	["HEIRLOOMS_UPDATED"] = function(...) GameEvent.HandleHeirloomsUpdated(...) end,
	["HIDE_HYPERLINK_TOOLTIP"] = function(...) GameEvent.HandleHideHyperlinkTooltip(...) end,
	["INSTANCE_RESET_WARNING"] = function(...) GameEvent.HandleInstanceResetWarning(...) end,
	["INVITE_TO_PARTY_CONFIRMATION"] = function(...) GameEvent.HandleInviteToPartyConfirmation(...) end,
	["ISLAND_COMPLETED"] = function(...) GameEvent.HandleIslandCompleted(...) end,
	["LEAVING_TUTORIAL_AREA"] = function(...) GameEvent.HandleLeavingTutorialArea(...) end,
	["LOADING_SCREEN_DISABLED"] = function(...) GameEvent.HandleLoadingScreenDisabled(...) end,
	["LOADING_SCREEN_ENABLED"] = function(...) GameEvent.HandleLoadingScreenEnabled(...) end,
	["LOOT_BIND_CONFIRM"] = function(...) GameEvent.HandleLootBindConfirm(...) end,
	["LOGOUT_CANCEL"] = function(...) GameEvent.HandleLogoutCancel(...) end,
	["MACRO_ACTION_BLOCKED"] = function(...) GameEvent.HandleActionBlocked(...) end,
	["MACRO_ACTION_FORBIDDEN"] = function(...) GameEvent.HandleMacroActionForbidden(...) end,
	["NOTCHED_DISPLAY_MODE_CHANGED"] = function(...) GameEvent.HandleNotchedDisplayModeChanged(...) end,
	["PARTY_INVITE_REQUEST"] = function(...) GameEvent.HandlePartyInviteRequest(...) end,
	["PERKS_PROGRAM_DISABLED"] = function(...) GameEvent.HandlePerksProgramDisabled(...) end,
	["PERKS_PROGRAM_OPEN"] = function(...) GameEvent.HandlePerksProgramOpen(...) end,
	["PET_BATTLE_PVP_DUEL_REQUEST_CANCEL"] = function(...) GameEvent.HandlePetBattlePvpDuelRequestCancel(...) end,
	["PET_BATTLE_PVP_DUEL_REQUESTED"] = function(...) GameEvent.HandlePetBattlePvpDuelRequested(...) end,
	["PET_BATTLE_QUEUE_PROPOSAL_ACCEPTED"] = function(...) GameEvent.HandlePetBattleQueueProposalResult(...) end,
	["PET_BATTLE_QUEUE_PROPOSAL_DECLINED"] = function(...) GameEvent.HandlePetBattleQueueProposalResult(...) end,
	["PET_BATTLE_QUEUE_PROPOSE_MATCH"] = function(...) GameEvent.HandlePetBattleQueueProposeMatch(...) end,
	["PING_SYSTEM_ERROR"] = function(...) GameEvent.HandlePingSystemError(...) end,
	["PLAYER_ALIVE"] = function(...) GameEvent.HandlePlayerAlive(...) end,
	["PLAYER_CHOICE_UPDATE"] = function(...) GameEvent.HandlePlayerChoiceUpdate(...) end,
	["PLAYER_DEAD"] = function(...) GameEvent.HandlePlayerDead(...) end,
	["PLAYER_SOFT_INTERACT_CHANGED"] = function(...) GameEvent.HandlePlayerSoftInteractChanged(...) end,
	["PLAYER_UNGHOST"] = function(...) GameEvent.HandlePlayerUnghost(...) end,
	["PRODUCT_DISTRIBUTIONS_UPDATED"] = function(...) GameEvent.HandleProductDistributionsUpdated(...) end,
	["PROFESSION_EQUIPMENT_CHANGED"] = function(...) GameEvent.HandleProfessionEquipmentChanged(...) end,
	["PROFESSION_RESPEC_CONFIRMATION"] = function(...) GameEvent.HandleProfessionRespecConfirmation(...) end,
	["PVP_BRAWL_INFO_UPDATED"] = function(...) GameEvent.HandleUpdateBattlefieldStatus(...) end,
	["QUEST_ACCEPT_CONFIRM"] = function(...) GameEvent.HandleQuestAcceptConfirm(...) end,
	["RAID_INSTANCE_WELCOME"] = function(...) GameEvent.HandleRaidInstanceWelcome(...) end,
	["RAISED_AS_GHOUL"] = function(...) GameEvent.HandlePlayerAlive(...) end,
	["REMIX_ARTIFACT_UPDATE"] = function(...) GameEvent.HandleRemixArtifactUpdate(...) end,
	["REMIX_END_OF_EVENT"] = function(...) GameEvent.HandleRemixEndOfEvent(...) end,
	["REPLACE_TRADESKILL_ENCHANT"] = function(...) GameEvent.HandleReplaceTradeskillEnchant(...) end,
	["RESURRECT_REQUEST"] = function(...) GameEvent.HandleResurrectRequest(...) end,
	["RUNEFORGE_LEGENDARY_CRAFTING_OPENED"] = function(...) GameEvent.HandleRuneforgeLegendaryCraftingOpened(...) end,
	["SCENARIO_UPDATE"] = function(...) GameEvent.HandleScenarioUpdate(...) end,
	["SCRIPTED_ANIMATIONS_UPDATE"] = function(...) GameEvent.HandleScriptedAnimationsUpdate(...) end,
	["SELF_RES_SPELL_CHANGED"] = function(...) GameEvent.HandleSelfResSpellChanged(...) end,
	["SETTINGS_LOADED"] = function(...) GameEvent.HandleSettingsLoaded(...) end,
	["SHIPMENT_CRAFTER_OPENED"] = function(...) GameEvent.HandleShipmentCrafterOpened(...) end,
	["SHOW_HYPERLINK_TOOLTIP"] = function(...) GameEvent.HandleShowHyperlinkTooltip(...) end,
	["SHOW_JOURNEYS_UI"] = function(...) GameEvent.HandleShowJourneysUi(...) end,
	["SHOW_PARTY_POSE_UI"] = function(...) GameEvent.HandleShowPartyPoseUi(...) end,
	["SOCKET_INFO_UPDATE"] = function(...) GameEvent.HandleSocketInfoUpdate(...) end,
	["SPEC_INVOLUNTARILY_CHANGED"] = function(...) GameEvent.HandleSpecInvoluntarilyChanged(...) end,
	["SPELL_CONFIRMATION_PROMPT"] = function(...) GameEvent.HandleSpellConfirmationPrompt(...) end,
	["SPELL_CONFIRMATION_TIMEOUT"] = function(...) GameEvent.HandleSpellConfirmationTimeout(...) end,
	["START_LOOT_ROLL"] = function(...) GameEvent.HandleStartLootRoll(...) end,
	["TAXIMAP_OPENED"] = function(...) GameEvent.HandleTaxiMapOpened(...) end,
	["TOKEN_AUCTION_SOLD"] = function(...) GameEvent.HandleTokenAuctionSold(...) end,
	["TOYS_UPDATED"] = function(...) GameEvent.HandleToysUpdated(...) end,
	["TRADE_SKILL_SHOW"] = function(...) GameEvent.HandleTradeSkillShow(...) end,
	["TRAIT_SYSTEM_INTERACTION_STARTED"] = function(...) GameEvent.HandleTraitSystemInteractionStarted(...) end,
	["TRANSMOG_COLLECTION_UPDATED"] = function(...) GameEvent.HandleTransmogCollectionUpdated(...) end,
	["UI_ERROR_POPUP"] = function(...) GameEvent.HandleUiErrorPopup(...) end,
	["UI_SCALE_CHANGED"] = function(...) GameEvent.HandleUiScaleChanged(...) end,
	["UPDATE_BATTLEFIELD_STATUS"] = function(...) GameEvent.HandleUpdateBattlefieldStatus(...) end,
	["UPDATE_SPELL_TARGET_ITEM_CONTEXT"] = function(...) GameEvent.HandleUpdateSpellTargetItemContext(...) end,
	["USE_GLYPH"] = function(...) GameEvent.HandleUseGlyph(...) end,
	["VARIABLES_LOADED"] = function(...) GameEvent.HandleVariablesLoaded(...) end,
	["WARFRONT_COMPLETED"] = function(...) GameEvent.HandleWarfrontCompleted(...) end,
	["WORLD_CURSOR_TOOLTIP_UPDATE"] = function(...) GameEvent.HandleWorldCursorTooltipUpdate(...) end,
};

function GameEvent.RegisterMainlineEvents()
	GameEvent.RegisterInternalEvents(eventHandlers);

	local function Callback()
		GameEvent.CheckNPETutorial();
	end

	-- SETTINGS_LOADED is emitted only after VARIABLES_LOADED and PLAYER_ENTERING_WORLD have both completed,
	-- which avoids racing the settings bootstrap and loading NPE before tutorials have been initialized.
	EventUtil.RegisterOnceFrameEventAndCallback("SETTINGS_LOADED", Callback);
end

function GameEvent.InitEvents()
	GameEvent.RegisterSharedEvents();
	GameEvent.RegisterMainlineEvents();
end
