local eventHandlers = {
	["ADDON_ACTION_BLOCKED"] = GameEvent.HandleActionBlocked,
	["ADVENTURE_MAP_OPEN"] = GameEvent.HandleAdventureMapOpen,
	["ALLIED_RACE_OPEN"] = GameEvent.HandleAlliedRaceOpen,
	["ANIMA_DIVERSION_OPEN"] = GameEvent.HandleAnimaDiversionOpen,
	["ARTIFACT_ENDGAME_REFUND"] = GameEvent.HandleArtifactEndgameRefund,
	["ARTIFACT_RELIC_FORGE_UPDATE"] = GameEvent.HandleArtifactRelicForgeUpdate,
	["ARTIFACT_RESPEC_PROMPT"] = GameEvent.HandleArtifactRespecPrompt,
	["ARTIFACT_UPDATE"] = GameEvent.HandleArtifactUpdate,
	["AUCTION_HOUSE_CLOSED"] = GameEvent.HandleAuctionHouseClosed,
	["AUCTION_HOUSE_DISABLED"] = GameEvent.HandleAuctionHouseDisabled,
	["AUCTION_HOUSE_SHOW"] = GameEvent.HandleAuctionHouseShow,
	["AUCTION_HOUSE_SHOW_FORMATTED_NOTIFICATION"] = GameEvent.HandleAuctionHouseNotification,
	["AUCTION_HOUSE_SHOW_NOTIFICATION"] = GameEvent.HandleAuctionHouseNotification,
	["BARBER_SHOP_CLOSE"] = GameEvent.HandleBarberShopClose,
	["CHALLENGE_MODE_COMPLETED"] = GameEvent.HandleChallengeModeCompleted,
	["CHALLENGE_MODE_KEYSTONE_RECEPTABLE_OPEN"] = GameEvent.HandleChallengeModeKeystoneReceptableOpen,
	["CONFIRM_DISENCHANT_ROLL"] = GameEvent.HandleConfirmDisenchantRoll,
	["CONFIRM_TALENT_WIPE"] = GameEvent.HandleConfirmTalentWipe,
	["CONFIRM_XP_LOSS"] = GameEvent.HandleConfirmXpLoss,
	["CONVERT_TO_BIND_TO_ACCOUNT_CONFIRM"] = GameEvent.HandleConvertToBindToAccountConfirm,
	["CORPSE_IN_INSTANCE"] = GameEvent.HandleCorpseInInstance,
	["CORPSE_IN_RANGE"] = GameEvent.HandleCorpseInRange,
	["CORPSE_OUT_OF_RANGE"] = GameEvent.HandleCorpseOutOfRange,
	["COVENANT_PREVIEW_OPEN"] = GameEvent.HandleCovenantPreviewOpen,
	["CRAFTING_HOUSE_DISABLED"] = GameEvent.HandleCraftingHouseDisabled,
	["CRAFTINGORDERS_HIDE_CUSTOMER"] = GameEvent.HandleCraftingOrdersHideCustomer,
	["CRAFTINGORDERS_SHOW_CUSTOMER"] = GameEvent.HandleCraftingOrdersShowCustomer,
	["CURRENT_SPELL_CAST_CHANGED"] = GameEvent.HandleCurrentSpellCastChanged,
	["CVAR_UPDATE"] = GameEvent.HandleCvarUpdate,
	["DAILY_RESET_INSTANCE_WELCOME"] = GameEvent.HandleDailyResetInstanceWelcome,
	["DELETE_ITEM_CONFIRM"] = GameEvent.HandleDeleteItemConfirm,
	["DISABLE_TAXI_BENCHMARK"] = GameEvent.HandleDisableTaxiBenchmark,
	["DUEL_FINISHED"] = GameEvent.HandleDuelFinished,
	["ENABLE_TAXI_BENCHMARK"] = GameEvent.HandleEnableTaxiBenchmark,
	["ENCHANT_SPELL_SELECTED"] = GameEvent.HandleEnchantSpellSelected,
	["EQUIP_BIND_CONFIRM"] = GameEvent.HandleEquipBindConfirm,
	["EQUIP_BIND_REFUNDABLE_CONFIRM"] = GameEvent.HandleEquipBindRefundableConfirm,
	["EQUIP_BIND_TRADEABLE_CONFIRM"] = GameEvent.HandleEquipBindTradeableConfirm,
	["GARRISON_MISSION_NPC_CLOSED"] = GameEvent.HandleGarrisonMissionNpcClosed,
	["GARRISON_MISSION_NPC_OPENED"] = GameEvent.HandleGarrisonMissionNpcOpened,
	["GARRISON_RECRUITMENT_NPC_OPENED"] = GameEvent.HandleGarrisonRecruitmentNpcOpened,
	["GARRISON_SHIPYARD_NPC_CLOSED"] = GameEvent.HandleGarrisonShipyardNpcClosed,
	["GARRISON_SHIPYARD_NPC_OPENED"] = GameEvent.HandleGarrisonShipyardNpcOpened,
	["GARRISON_TALENT_NPC_OPENED"] = GameEvent.HandleGarrisonTalentNpcOpened,
	["GET_ITEM_INFO_RECEIVED"] = GameEvent.HandleGetItemInfoReceived,
	["GLOBAL_MOUSE_DOWN"] = GameEvent.HandleGlobalMouseEvent,
	["GLOBAL_MOUSE_UP"] = GameEvent.HandleGlobalMouseEvent,
	["GROUP_INVITE_CONFIRMATION"] = GameEvent.HandleGroupInviteConfirmation,
	["HEIRLOOM_UPGRADE_TARGETING_CHANGED"] = GameEvent.HandleHeirloomUpgradeTargetingChanged,
	["HEIRLOOMS_UPDATED"] = GameEvent.HandleHeirloomsUpdated,
	["HIDE_HYPERLINK_TOOLTIP"] = GameEvent.HandleHideHyperlinkTooltip,
	["INSTANCE_RESET_WARNING"] = GameEvent.HandleInstanceResetWarning,
	["INVITE_TO_PARTY_CONFIRMATION"] = GameEvent.HandleInviteToPartyConfirmation,
	["ISLAND_COMPLETED"] = GameEvent.HandleIslandCompleted,
	["LEAVING_TUTORIAL_AREA"] = GameEvent.HandleLeavingTutorialArea,
	["LOADING_SCREEN_DISABLED"] = GameEvent.HandleLoadingScreenDisabled,
	["LOADING_SCREEN_ENABLED"] = GameEvent.HandleLoadingScreenEnabled,
	["LOOT_BIND_CONFIRM"] = GameEvent.HandleLootBindConfirm,
	["LOGOUT_CANCEL"] = GameEvent.HandleLogoutCancel,
	["MACRO_ACTION_BLOCKED"] = GameEvent.HandleActionBlocked,
	["MACRO_ACTION_FORBIDDEN"] = GameEvent.HandleMacroActionForbidden,
	["NOTCHED_DISPLAY_MODE_CHANGED"] = GameEvent.HandleNotchedDisplayModeChanged,
	["PARTY_INVITE_REQUEST"] = GameEvent.HandlePartyInviteRequest,
	["PERKS_PROGRAM_DISABLED"] = GameEvent.HandlePerksProgramDisabled,
	["PERKS_PROGRAM_OPEN"] = GameEvent.HandlePerksProgramOpen,
	["PET_BATTLE_PVP_DUEL_REQUEST_CANCEL"] = GameEvent.HandlePetBattlePvpDuelRequestCancel,
	["PET_BATTLE_PVP_DUEL_REQUESTED"] = GameEvent.HandlePetBattlePvpDuelRequested,
	["PET_BATTLE_QUEUE_PROPOSAL_ACCEPTED"] = GameEvent.HandlePetBattleQueueProposalResult,
	["PET_BATTLE_QUEUE_PROPOSAL_DECLINED"] = GameEvent.HandlePetBattleQueueProposalResult,
	["PET_BATTLE_QUEUE_PROPOSE_MATCH"] = GameEvent.HandlePetBattleQueueProposeMatch,
	["PING_SYSTEM_ERROR"] = GameEvent.HandlePingSystemError,
	["PLAYER_ALIVE"] = GameEvent.HandlePlayerAlive,
	["PLAYER_CHOICE_UPDATE"] = GameEvent.HandlePlayerChoiceUpdate,
	["PLAYER_DEAD"] = GameEvent.HandlePlayerDead,
	["PLAYER_SOFT_INTERACT_CHANGED"] = GameEvent.HandlePlayerSoftInteractChanged,
	["PLAYER_UNGHOST"] = GameEvent.HandlePlayerUnghost,
	["PRODUCT_DISTRIBUTIONS_UPDATED"] = GameEvent.HandleProductDistributionsUpdated,
	["PROFESSION_EQUIPMENT_CHANGED"] = GameEvent.HandleProfessionEquipmentChanged,
	["PROFESSION_RESPEC_CONFIRMATION"] = GameEvent.HandleProfessionRespecConfirmation,
	["PVP_BRAWL_INFO_UPDATED"] = GameEvent.HandleUpdateBattlefieldStatus,
	["QUEST_ACCEPT_CONFIRM"] = GameEvent.HandleQuestAcceptConfirm,
	["RAID_INSTANCE_WELCOME"] = GameEvent.HandleRaidInstanceWelcome,
	["RAISED_AS_GHOUL"] = GameEvent.HandlePlayerAlive,
	["REMIX_ARTIFACT_UPDATE"] = GameEvent.HandleRemixArtifactUpdate,
	["REMIX_END_OF_EVENT"] = GameEvent.HandleRemixEndOfEvent,
	["REPLACE_TRADESKILL_ENCHANT"] = GameEvent.HandleReplaceTradeskillEnchant,
	["RESURRECT_REQUEST"] = GameEvent.HandleResurrectRequest,
	["RUNEFORGE_LEGENDARY_CRAFTING_OPENED"] = GameEvent.HandleRuneforgeLegendaryCraftingOpened,
	["SCENARIO_UPDATE"] = GameEvent.HandleScenarioUpdate,
	["SCRIPTED_ANIMATIONS_UPDATE"] = GameEvent.HandleScriptedAnimationsUpdate,
	["SELF_RES_SPELL_CHANGED"] = GameEvent.HandleSelfResSpellChanged,
	["SETTINGS_LOADED"] = GameEvent.HandleSettingsLoaded,
	["SHIPMENT_CRAFTER_OPENED"] = GameEvent.HandleShipmentCrafterOpened,
	["SHOW_HYPERLINK_TOOLTIP"] = GameEvent.HandleShowHyperlinkTooltip,
	["SHOW_JOURNEYS_UI"] = GameEvent.HandleShowJourneysUi,
	["SHOW_PARTY_POSE_UI"] = GameEvent.HandleShowPartyPoseUi,
	["SOCKET_INFO_UPDATE"] = GameEvent.HandleSocketInfoUpdate,
	["SPEC_INVOLUNTARILY_CHANGED"] = GameEvent.HandleSpecInvoluntarilyChanged,
	["SPELL_CONFIRMATION_PROMPT"] = GameEvent.HandleSpellConfirmationPrompt,
	["SPELL_CONFIRMATION_TIMEOUT"] = GameEvent.HandleSpellConfirmationTimeout,
	["START_LOOT_ROLL"] = GameEvent.HandleStartLootRoll,
	["TAXIMAP_OPENED"] = GameEvent.HandleTaxiMapOpened,
	["TOKEN_AUCTION_SOLD"] = GameEvent.HandleTokenAuctionSold,
	["TOYS_UPDATED"] = GameEvent.HandleToysUpdated,
	["TRADE_SKILL_SHOW"] = GameEvent.HandleTradeSkillShow,
	["TRAIT_SYSTEM_INTERACTION_STARTED"] = GameEvent.HandleTraitSystemInteractionStarted,
	["TRANSMOG_COLLECTION_UPDATED"] = GameEvent.HandleTransmogCollectionUpdated,
	["UI_ERROR_POPUP"] = GameEvent.HandleUiErrorPopup,
	["UI_SCALE_CHANGED"] = GameEvent.HandleUiScaleChanged,
	["UPDATE_BATTLEFIELD_STATUS"] = GameEvent.HandleUpdateBattlefieldStatus,
	["UPDATE_SPELL_TARGET_ITEM_CONTEXT"] = GameEvent.HandleUpdateSpellTargetItemContext,
	["USE_GLYPH"] = GameEvent.HandleUseGlyph,
	["VARIABLES_LOADED"] = GameEvent.HandleVariablesLoaded,
	["WARFRONT_COMPLETED"] = GameEvent.HandleWarfrontCompleted,
	["WORLD_CURSOR_TOOLTIP_UPDATE"] = GameEvent.HandleWorldCursorTooltipUpdate,
};

function GameEvent.RegisterMainlineEvents()
	GameEvent.RegisterInternalEvents(eventHandlers);

	local function Callback()
		GameEvent.CheckNPETutorial();
	end

	-- SETTINGS_LOADED is emitted only after VARIABLES_LOADED and PLAYER_ENTERING_WORLD have both completed,
	-- which avoids racing the settings bootstrap and loading NPE before tutorials have been initialized.
	EventUtil.RegisterOnceFrameEventAndCallback("SETTINGS_LOADED", Callback);
end

function GameEvent.InitEvents()
	GameEvent.RegisterSharedEvents();
	GameEvent.RegisterMainlineEvents();
end
