local BattlepayConstants =
{
	Tables =
	{
		{
			Name = "CanRedeemTokenForBalanceResult",
			Type = "Enumeration",
			NumValues = 2,
			MinValue = 0,
			MaxValue = 1,
			Fields =
			{
				{ Name = "Ok", Type = "CanRedeemTokenForBalanceResult", EnumValue = 0 },
				{ Name = "FailureCap", Type = "CanRedeemTokenForBalanceResult", EnumValue = 1 },
			},
		},
		{
			Name = "VasTransactionPurchaseResult",
			Type = "Enumeration",
			NumValues = 144,
			MinValue = 0,
			MaxValue = 20096,
			Fields =
			{
				{ Name = "None", Type = "VasTransactionPurchaseResult", EnumValue = 0 },
				{ Name = "VasPurchaseDisabled", Type = "VasTransactionPurchaseResult", EnumValue = 1 },
				{ Name = "NoneCharacter", Type = "VasTransactionPurchaseResult", EnumValue = 2 },
				{ Name = "NoneProduct", Type = "VasTransactionPurchaseResult", EnumValue = 3 },
				{ Name = "OnlyOneVasAtATime", Type = "VasTransactionPurchaseResult", EnumValue = 4 },
				{ Name = "InvalidDestinationRealm", Type = "VasTransactionPurchaseResult", EnumValue = 5 },
				{ Name = "InvalidDestinationAccount", Type = "VasTransactionPurchaseResult", EnumValue = 6 },
				{ Name = "InvalidSourceAccount", Type = "VasTransactionPurchaseResult", EnumValue = 7 },
				{ Name = "DisallowedSourceAccount", Type = "VasTransactionPurchaseResult", EnumValue = 8 },
				{ Name = "DisallowedDestinationAccount", Type = "VasTransactionPurchaseResult", EnumValue = 9 },
				{ Name = "UnknownError", Type = "VasTransactionPurchaseResult", EnumValue = 10 },
				{ Name = "LowerBoxLevel", Type = "VasTransactionPurchaseResult", EnumValue = 11 },
				{ Name = "InvalidDistribution", Type = "VasTransactionPurchaseResult", EnumValue = 12 },
				{ Name = "InvalidBpayProductID", Type = "VasTransactionPurchaseResult", EnumValue = 13 },
				{ Name = "InvalidBpayDeliverableID", Type = "VasTransactionPurchaseResult", EnumValue = 14 },
				{ Name = "InvalidBpayProductType", Type = "VasTransactionPurchaseResult", EnumValue = 15 },
				{ Name = "EndServerErrors", Type = "VasTransactionPurchaseResult", EnumValue = 16 },
				{ Name = "BeginProxyErrors", Type = "VasTransactionPurchaseResult", EnumValue = 17 },
				{ Name = "ProxyBadObjType", Type = "VasTransactionPurchaseResult", EnumValue = 18 },
				{ Name = "ProxyObjNotInDb", Type = "VasTransactionPurchaseResult", EnumValue = 19 },
				{ Name = "ProxyUniqueKey", Type = "VasTransactionPurchaseResult", EnumValue = 20 },
				{ Name = "ProxyDbError", Type = "VasTransactionPurchaseResult", EnumValue = 21 },
				{ Name = "ProxyDataInvalid", Type = "VasTransactionPurchaseResult", EnumValue = 22 },
				{ Name = "ProxyLostProxyConnection", Type = "VasTransactionPurchaseResult", EnumValue = 23 },
				{ Name = "ProxyLocksFailed", Type = "VasTransactionPurchaseResult", EnumValue = 24 },
				{ Name = "ProxyMissingResultsPtr", Type = "VasTransactionPurchaseResult", EnumValue = 25 },
				{ Name = "ProxyLockedForTransfer", Type = "VasTransactionPurchaseResult", EnumValue = 26 },
				{ Name = "ProxyNoReturnValue", Type = "VasTransactionPurchaseResult", EnumValue = 27 },
				{ Name = "ProxyDeleteNotSupported", Type = "VasTransactionPurchaseResult", EnumValue = 28 },
				{ Name = "ProxyObjDropped", Type = "VasTransactionPurchaseResult", EnumValue = 29 },
				{ Name = "ProxyCannotDeleteGuildLeader", Type = "VasTransactionPurchaseResult", EnumValue = 30 },
				{ Name = "ProxyCannotDeleteArenaCaptain", Type = "VasTransactionPurchaseResult", EnumValue = 31 },
				{ Name = "ProxyMoneyLimitExceeded", Type = "VasTransactionPurchaseResult", EnumValue = 32 },
				{ Name = "ProxyBadRequestContained", Type = "VasTransactionPurchaseResult", EnumValue = 33 },
				{ Name = "ProxyIsReadonly", Type = "VasTransactionPurchaseResult", EnumValue = 34 },
				{ Name = "ProxyBadDbType", Type = "VasTransactionPurchaseResult", EnumValue = 35 },
				{ Name = "ProxyOperationAlreadyInProgress", Type = "VasTransactionPurchaseResult", EnumValue = 36 },
				{ Name = "ProxyExternalUpdateDetected", Type = "VasTransactionPurchaseResult", EnumValue = 37 },
				{ Name = "ProxyCharacterLevelTooHigh", Type = "VasTransactionPurchaseResult", EnumValue = 38 },
				{ Name = "ProxyCharacterTransferred", Type = "VasTransactionPurchaseResult", EnumValue = 39 },
				{ Name = "ProxyCharacterTransferredNoBoostInProgress", Type = "VasTransactionPurchaseResult", EnumValue = 40 },
				{ Name = "ProxyLockedForUpgrade", Type = "VasTransactionPurchaseResult", EnumValue = 41 },
				{ Name = "ProxyLockedForToken", Type = "VasTransactionPurchaseResult", EnumValue = 42 },
				{ Name = "ProxyLockedForVas", Type = "VasTransactionPurchaseResult", EnumValue = 43 },
				{ Name = "ProxyGenericError", Type = "VasTransactionPurchaseResult", EnumValue = 44 },
				{ Name = "ProxyCannotInsertNull", Type = "VasTransactionPurchaseResult", EnumValue = 45 },
				{ Name = "ProxyCannotUndeleteTrialBoostCharacter", Type = "VasTransactionPurchaseResult", EnumValue = 46 },
				{ Name = "ProxyPredicateFailed", Type = "VasTransactionPurchaseResult", EnumValue = 47 },
				{ Name = "ProxyWeeklyRewardNotFound", Type = "VasTransactionPurchaseResult", EnumValue = 48 },
				{ Name = "ProxyInsertRequestContainedNoData", Type = "VasTransactionPurchaseResult", EnumValue = 49 },
				{ Name = "ProxyInvalidKey", Type = "VasTransactionPurchaseResult", EnumValue = 50 },
				{ Name = "ProxyBindFailed", Type = "VasTransactionPurchaseResult", EnumValue = 51 },
				{ Name = "ProxyTooManyRows", Type = "VasTransactionPurchaseResult", EnumValue = 52 },
				{ Name = "ProxyCharacterHasWoWToken", Type = "VasTransactionPurchaseResult", EnumValue = 53 },
				{ Name = "ProxyTooBusyBackOff", Type = "VasTransactionPurchaseResult", EnumValue = 54 },
				{ Name = "ProxyAccountDataTooBig", Type = "VasTransactionPurchaseResult", EnumValue = 55 },
				{ Name = "EndProxyErrors", Type = "VasTransactionPurchaseResult", EnumValue = 56 },
				{ Name = "BeginDbErrors", Type = "VasTransactionPurchaseResult", EnumValue = 20010 },
				{ Name = "DbRealmNotEligible", Type = "VasTransactionPurchaseResult", EnumValue = 20011 },
				{ Name = "DbCannotMoveGuildmaster", Type = "VasTransactionPurchaseResult", EnumValue = 20012 },
				{ Name = "DbMaxCharactersOnServer", Type = "VasTransactionPurchaseResult", EnumValue = 20013 },
				{ Name = "DbNoMixedAlliance", Type = "VasTransactionPurchaseResult", EnumValue = 20014 },
				{ Name = "DbDuplicateCharacterName", Type = "VasTransactionPurchaseResult", EnumValue = 20015 },
				{ Name = "DbHasMail", Type = "VasTransactionPurchaseResult", EnumValue = 20016 },
				{ Name = "DbAccountDoesNotOwnCharacter", Type = "VasTransactionPurchaseResult", EnumValue = 20017 },
				{ Name = "DbMoveInProgress", Type = "VasTransactionPurchaseResult", EnumValue = 20018 },
				{ Name = "DbCharacterDoesNotExist", Type = "VasTransactionPurchaseResult", EnumValue = 20019 },
				{ Name = "DbNoCopiesAvailable", Type = "VasTransactionPurchaseResult", EnumValue = 20020 },
				{ Name = "DbUnderMinLevelReq", Type = "VasTransactionPurchaseResult", EnumValue = 20021 },
				{ Name = "DbIneligibleTargetRealm", Type = "VasTransactionPurchaseResult", EnumValue = 20022 },
				{ Name = "DbTransferDateTooSoon", Type = "VasTransactionPurchaseResult", EnumValue = 20023 },
				{ Name = "DbNewNameTooLong", Type = "VasTransactionPurchaseResult", EnumValue = 20024 },
				{ Name = "DbCharNotLocked", Type = "VasTransactionPurchaseResult", EnumValue = 20025 },
				{ Name = "DbCharLocked", Type = "VasTransactionPurchaseResult", EnumValue = 20026 },
				{ Name = "DbAllianceNotEligible", Type = "VasTransactionPurchaseResult", EnumValue = 20027 },
				{ Name = "DbBatchProcessingDisabled", Type = "VasTransactionPurchaseResult", EnumValue = 20028 },
				{ Name = "DbNoneBatchQueueID", Type = "VasTransactionPurchaseResult", EnumValue = 20029 },
				{ Name = "DbTransferNotFinalized", Type = "VasTransactionPurchaseResult", EnumValue = 20030 },
				{ Name = "DbTransferNotCancellable", Type = "VasTransactionPurchaseResult", EnumValue = 20031 },
				{ Name = "DbTooMuchMoneyForLevel", Type = "VasTransactionPurchaseResult", EnumValue = 20032 },
				{ Name = "DbHasAuctions", Type = "VasTransactionPurchaseResult", EnumValue = 20033 },
				{ Name = "DbLastSaveTooRecent", Type = "VasTransactionPurchaseResult", EnumValue = 20034 },
				{ Name = "DbTransferNotLockable", Type = "VasTransactionPurchaseResult", EnumValue = 20035 },
				{ Name = "DbTransferNotUnlockable", Type = "VasTransactionPurchaseResult", EnumValue = 20036 },
				{ Name = "DbNoneRealmForEvent", Type = "VasTransactionPurchaseResult", EnumValue = 20037 },
				{ Name = "DbEventRealmClosed", Type = "VasTransactionPurchaseResult", EnumValue = 20038 },
				{ Name = "DbNoneTemplateForEvent", Type = "VasTransactionPurchaseResult", EnumValue = 20039 },
				{ Name = "DbInventoryCorrupt", Type = "VasTransactionPurchaseResult", EnumValue = 20040 },
				{ Name = "DbCouldNotObtainCharLock", Type = "VasTransactionPurchaseResult", EnumValue = 20041 },
				{ Name = "DbNoneLockID", Type = "VasTransactionPurchaseResult", EnumValue = 20042 },
				{ Name = "DbLockNotAcknowledged", Type = "VasTransactionPurchaseResult", EnumValue = 20043 },
				{ Name = "DbLockAlreadyRequested", Type = "VasTransactionPurchaseResult", EnumValue = 20044 },
				{ Name = "DbNoneSupportQueueID", Type = "VasTransactionPurchaseResult", EnumValue = 20045 },
				{ Name = "DbNoneSupportActionID", Type = "VasTransactionPurchaseResult", EnumValue = 20046 },
				{ Name = "DbNotRollbackable", Type = "VasTransactionPurchaseResult", EnumValue = 20047 },
				{ Name = "DbNotMovebackable", Type = "VasTransactionPurchaseResult", EnumValue = 20048 },
				{ Name = "DbRenameAlreadyRequested", Type = "VasTransactionPurchaseResult", EnumValue = 20049 },
				{ Name = "DbReservationExpired", Type = "VasTransactionPurchaseResult", EnumValue = 20050 },
				{ Name = "DbNameNotAvailable", Type = "VasTransactionPurchaseResult", EnumValue = 20051 },
				{ Name = "DbLastRenameTooRecent", Type = "VasTransactionPurchaseResult", EnumValue = 20052 },
				{ Name = "DbReservationDoesNotMatch", Type = "VasTransactionPurchaseResult", EnumValue = 20053 },
				{ Name = "DbLastRequestTooSoon", Type = "VasTransactionPurchaseResult", EnumValue = 20054 },
				{ Name = "DbAlreadyRenameFlagged", Type = "VasTransactionPurchaseResult", EnumValue = 20055 },
				{ Name = "DbMultipleTransferCn", Type = "VasTransactionPurchaseResult", EnumValue = 20056 },
				{ Name = "DbCustomizeAlreadyRequested", Type = "VasTransactionPurchaseResult", EnumValue = 20057 },
				{ Name = "DbLastCustomizeTooSoon", Type = "VasTransactionPurchaseResult", EnumValue = 20058 },
				{ Name = "DbWaitingForPayment", Type = "VasTransactionPurchaseResult", EnumValue = 20059 },
				{ Name = "DbUnableToCustomize", Type = "VasTransactionPurchaseResult", EnumValue = 20060 },
				{ Name = "DbFactionChangeTooSoon", Type = "VasTransactionPurchaseResult", EnumValue = 20061 },
				{ Name = "DbRaceClassComboIneligible", Type = "VasTransactionPurchaseResult", EnumValue = 20062 },
				{ Name = "DbDuplicateSupportRequest", Type = "VasTransactionPurchaseResult", EnumValue = 20063 },
				{ Name = "DbCannotMoveArenaCaptn", Type = "VasTransactionPurchaseResult", EnumValue = 20064 },
				{ Name = "DbNoCsiFound", Type = "VasTransactionPurchaseResult", EnumValue = 20065 },
				{ Name = "DbPendingItemAudit", Type = "VasTransactionPurchaseResult", EnumValue = 20066 },
				{ Name = "DbBatchStateInvalid", Type = "VasTransactionPurchaseResult", EnumValue = 20067 },
				{ Name = "DbEventNotActive", Type = "VasTransactionPurchaseResult", EnumValue = 20068 },
				{ Name = "DbGuildRankInsufficient", Type = "VasTransactionPurchaseResult", EnumValue = 20069 },
				{ Name = "DbCharacterWithoutGuild", Type = "VasTransactionPurchaseResult", EnumValue = 20070 },
				{ Name = "DbDeletedGuild", Type = "VasTransactionPurchaseResult", EnumValue = 20071 },
				{ Name = "DbGmSenorityInsufficient", Type = "VasTransactionPurchaseResult", EnumValue = 20072 },
				{ Name = "DbAuthenticatorInsufficient", Type = "VasTransactionPurchaseResult", EnumValue = 20073 },
				{ Name = "DbGuildLevelInsufficient", Type = "VasTransactionPurchaseResult", EnumValue = 20074 },
				{ Name = "DbRegionalDbNotFound", Type = "VasTransactionPurchaseResult", EnumValue = 20075 },
				{ Name = "DbIneligibleMapID", Type = "VasTransactionPurchaseResult", EnumValue = 20076 },
				{ Name = "DbBnetAccountNotProvided", Type = "VasTransactionPurchaseResult", EnumValue = 20077 },
				{ Name = "DbBpayDeliveryPending", Type = "VasTransactionPurchaseResult", EnumValue = 20078 },
				{ Name = "DbHasBpayToken", Type = "VasTransactionPurchaseResult", EnumValue = 20079 },
				{ Name = "DbHasHeirloomItem", Type = "VasTransactionPurchaseResult", EnumValue = 20080 },
				{ Name = "DbResultSourceAccountBanned", Type = "VasTransactionPurchaseResult", EnumValue = 20081 },
				{ Name = "DbResultAccountRestricted", Type = "VasTransactionPurchaseResult", EnumValue = 20082 },
				{ Name = "DbLastSaveTooDistant", Type = "VasTransactionPurchaseResult", EnumValue = 20083 },
				{ Name = "DbCagedPetInInventory", Type = "VasTransactionPurchaseResult", EnumValue = 20084 },
				{ Name = "DbOnBoostCooldown", Type = "VasTransactionPurchaseResult", EnumValue = 20085 },
				{ Name = "DbNewLeaderInvalid", Type = "VasTransactionPurchaseResult", EnumValue = 20086 },
				{ Name = "DbPvEPvPTransferNotAllowed", Type = "VasTransactionPurchaseResult", EnumValue = 20087 },
				{ Name = "DbNeedsLevelSquish", Type = "VasTransactionPurchaseResult", EnumValue = 20088 },
				{ Name = "DbHasUnclaimedCacheRewards", Type = "VasTransactionPurchaseResult", EnumValue = 20089 },
				{ Name = "DbNeedsEraChoice", Type = "VasTransactionPurchaseResult", EnumValue = 20090 },
				{ Name = "DbHasNewPlayerExperienceRestriction", Type = "VasTransactionPurchaseResult", EnumValue = 20091 },
				{ Name = "DbHasCraftingOrders", Type = "VasTransactionPurchaseResult", EnumValue = 20092 },
				{ Name = "DbNameChangeSkipped", Type = "VasTransactionPurchaseResult", EnumValue = 20093 },
				{ Name = "DbInvalidName", Type = "VasTransactionPurchaseResult", EnumValue = 20094 },
				{ Name = "DbBoostProcessingDisabled", Type = "VasTransactionPurchaseResult", EnumValue = 20095 },
				{ Name = "EndDbErrors", Type = "VasTransactionPurchaseResult", EnumValue = 20096 },
			},
		},
	},
};

APIDocumentation:AddDocumentationTable(BattlepayConstants);