local CooldownViewerConstants =
{
	Tables =
	{
		{
			Name = "CooldownSetLinkedSpellFlags",
			Type = "Enumeration",
			NumValues = 1,
			MinValue = 1,
			MaxValue = 1,
			Fields =
			{
				{ Name = "UseAsTooltip", Type = "CooldownSetLinkedSpellFlags", EnumValue = 1 },
			},
		},
		{
			Name = "CooldownSetSpellFlags",
			Type = "Enumeration",
			NumValues = 2,
			MinValue = 1,
			MaxValue = 2,
			Fields =
			{
				{ Name = "HideAura", Type = "CooldownSetSpellFlags", EnumValue = 1 },
				{ Name = "HideByDefault", Type = "CooldownSetSpellFlags", EnumValue = 2 },
			},
		},
		{
			Name = "CooldownViewerAddAlertStatus",
			Type = "Enumeration",
			NumValues = 4,
			MinValue = 0,
			MaxValue = 3,
			Fields =
			{
				{ Name = "Success", Type = "CooldownViewerAddAlertStatus", EnumValue = 0 },
				{ Name = "InvalidAlertType", Type = "CooldownViewerAddAlertStatus", EnumValue = 1 },
				{ Name = "InvalidEventType", Type = "CooldownViewerAddAlertStatus", EnumValue = 2 },
				{ Name = "DuplicateAlert", Type = "CooldownViewerAddAlertStatus", EnumValue = 3 },
			},
		},
		{
			Name = "CooldownViewerAlertEventType",
			Type = "Enumeration",
			NumValues = 6,
			MinValue = 1,
			MaxValue = 6,
			Fields =
			{
				{ Name = "Available", Type = "CooldownViewerAlertEventType", EnumValue = 1 },
				{ Name = "PandemicTime", Type = "CooldownViewerAlertEventType", EnumValue = 2 },
				{ Name = "OnCooldown", Type = "CooldownViewerAlertEventType", EnumValue = 3 },
				{ Name = "ChargeGained", Type = "CooldownViewerAlertEventType", EnumValue = 4 },
				{ Name = "OnAuraApplied", Type = "CooldownViewerAlertEventType", EnumValue = 5 },
				{ Name = "OnAuraRemoved", Type = "CooldownViewerAlertEventType", EnumValue = 6 },
			},
		},
		{
			Name = "CooldownViewerAlertType",
			Type = "Enumeration",
			NumValues = 2,
			MinValue = 1,
			MaxValue = 2,
			Fields =
			{
				{ Name = "Sound", Type = "CooldownViewerAlertType", EnumValue = 1 },
				{ Name = "Visual", Type = "CooldownViewerAlertType", EnumValue = 2 },
			},
		},
		{
			Name = "CooldownViewerCategory",
			Type = "Enumeration",
			NumValues = 9,
			MinValue = 0,
			MaxValue = 8,
			Fields =
			{
				{ Name = "Essential", Type = "CooldownViewerCategory", EnumValue = 0 },
				{ Name = "Utility", Type = "CooldownViewerCategory", EnumValue = 1 },
				{ Name = "TrackedBuff", Type = "CooldownViewerCategory", EnumValue = 2 },
				{ Name = "TrackedBar", Type = "CooldownViewerCategory", EnumValue = 3 },
				{ Name = "GroupBuff", Type = "CooldownViewerCategory", EnumValue = 4 },
				{ Name = "SpecAgnosticEssential", Type = "CooldownViewerCategory", EnumValue = 5 },
				{ Name = "SpecAgnosticTracked", Type = "CooldownViewerCategory", EnumValue = 6 },
				{ Name = "EquipSlotEssential", Type = "CooldownViewerCategory", EnumValue = 7 },
				{ Name = "EquipSlotTracked", Type = "CooldownViewerCategory", EnumValue = 8 },
			},
		},
		{
			Name = "CooldownViewerSound",
			Type = "Enumeration",
			NumValues = 94,
			MinValue = 0,
			MaxValue = 93,
			Fields =
			{
				{ Name = "TextToSpeech", Type = "CooldownViewerSound", EnumValue = 0 },
				{ Name = "AnimalsCat", Type = "CooldownViewerSound", EnumValue = 1 },
				{ Name = "AnimalsChicken", Type = "CooldownViewerSound", EnumValue = 2 },
				{ Name = "AnimalsCow", Type = "CooldownViewerSound", EnumValue = 3 },
				{ Name = "AnimalsGnoll", Type = "CooldownViewerSound", EnumValue = 4 },
				{ Name = "AnimalsGoat", Type = "CooldownViewerSound", EnumValue = 5 },
				{ Name = "AnimalsLion", Type = "CooldownViewerSound", EnumValue = 6 },
				{ Name = "AnimalsPanther", Type = "CooldownViewerSound", EnumValue = 7 },
				{ Name = "AnimalsRattlesnake", Type = "CooldownViewerSound", EnumValue = 8 },
				{ Name = "AnimalsSheep", Type = "CooldownViewerSound", EnumValue = 9 },
				{ Name = "AnimalsWolf", Type = "CooldownViewerSound", EnumValue = 10 },
				{ Name = "DevicesBoatHorn", Type = "CooldownViewerSound", EnumValue = 11 },
				{ Name = "DevicesAirHorn", Type = "CooldownViewerSound", EnumValue = 12 },
				{ Name = "DevicesBikeHorn", Type = "CooldownViewerSound", EnumValue = 13 },
				{ Name = "DevicesCashRegister", Type = "CooldownViewerSound", EnumValue = 14 },
				{ Name = "DevicesJackpotBell", Type = "CooldownViewerSound", EnumValue = 15 },
				{ Name = "DevicesJackpotCoins", Type = "CooldownViewerSound", EnumValue = 16 },
				{ Name = "DevicesJackpotFail", Type = "CooldownViewerSound", EnumValue = 17 },
				{ Name = "DevicesRotaryPhoneDial", Type = "CooldownViewerSound", EnumValue = 18 },
				{ Name = "DevicesRotaryPhoneRing", Type = "CooldownViewerSound", EnumValue = 19 },
				{ Name = "DevicesStovePipe", Type = "CooldownViewerSound", EnumValue = 20 },
				{ Name = "DevicesTrashcanLid", Type = "CooldownViewerSound", EnumValue = 21 },
				{ Name = "ImpactsAnvilStrike", Type = "CooldownViewerSound", EnumValue = 22 },
				{ Name = "ImpactsBubbleSmash", Type = "CooldownViewerSound", EnumValue = 23 },
				{ Name = "ImpactsLowThud", Type = "CooldownViewerSound", EnumValue = 24 },
				{ Name = "ImpactsMetalClanks", Type = "CooldownViewerSound", EnumValue = 25 },
				{ Name = "ImpactsMetalRattle", Type = "CooldownViewerSound", EnumValue = 26 },
				{ Name = "ImpactsMetalScrape", Type = "CooldownViewerSound", EnumValue = 27 },
				{ Name = "ImpactsMetalWarble", Type = "CooldownViewerSound", EnumValue = 28 },
				{ Name = "ImpactsPopClick", Type = "CooldownViewerSound", EnumValue = 29 },
				{ Name = "ImpactsStrangeClang", Type = "CooldownViewerSound", EnumValue = 30 },
				{ Name = "ImpactsSwordScrape", Type = "CooldownViewerSound", EnumValue = 31 },
				{ Name = "InstrumentsBellRing", Type = "CooldownViewerSound", EnumValue = 32 },
				{ Name = "InstrumentsBellTrill", Type = "CooldownViewerSound", EnumValue = 33 },
				{ Name = "InstrumentsBrass", Type = "CooldownViewerSound", EnumValue = 34 },
				{ Name = "InstrumentsChimeAscending", Type = "CooldownViewerSound", EnumValue = 35 },
				{ Name = "InstrumentsGuitarChug", Type = "CooldownViewerSound", EnumValue = 36 },
				{ Name = "InstrumentsGuitarPinch", Type = "CooldownViewerSound", EnumValue = 37 },
				{ Name = "InstrumentsPitchPipeDistressed", Type = "CooldownViewerSound", EnumValue = 38 },
				{ Name = "InstrumentsPitchPipeNote", Type = "CooldownViewerSound", EnumValue = 39 },
				{ Name = "InstrumentsSynthBig", Type = "CooldownViewerSound", EnumValue = 40 },
				{ Name = "InstrumentsSynthBuzz", Type = "CooldownViewerSound", EnumValue = 41 },
				{ Name = "InstrumentsSynthHigh", Type = "CooldownViewerSound", EnumValue = 42 },
				{ Name = "InstrumentsWarhorn", Type = "CooldownViewerSound", EnumValue = 43 },
				{ Name = "War2AbstractWhoosh", Type = "CooldownViewerSound", EnumValue = 44 },
				{ Name = "War2Choir", Type = "CooldownViewerSound", EnumValue = 45 },
				{ Name = "War2Construction", Type = "CooldownViewerSound", EnumValue = 46 },
				{ Name = "War2MagicChimes", Type = "CooldownViewerSound", EnumValue = 47 },
				{ Name = "War2PigSqueal", Type = "CooldownViewerSound", EnumValue = 48 },
				{ Name = "War2Saws", Type = "CooldownViewerSound", EnumValue = 49 },
				{ Name = "War2Seal", Type = "CooldownViewerSound", EnumValue = 50 },
				{ Name = "War2Slow", Type = "CooldownViewerSound", EnumValue = 51 },
				{ Name = "War2Smith", Type = "CooldownViewerSound", EnumValue = 52 },
				{ Name = "War2SynthStinger", Type = "CooldownViewerSound", EnumValue = 53 },
				{ Name = "War2TrumpetRally", Type = "CooldownViewerSound", EnumValue = 54 },
				{ Name = "War2ZippyMagic", Type = "CooldownViewerSound", EnumValue = 55 },
				{ Name = "War3Bell", Type = "CooldownViewerSound", EnumValue = 56 },
				{ Name = "War3CrunchyBell", Type = "CooldownViewerSound", EnumValue = 57 },
				{ Name = "War3DrumSplash", Type = "CooldownViewerSound", EnumValue = 58 },
				{ Name = "War3Error", Type = "CooldownViewerSound", EnumValue = 59 },
				{ Name = "War3Fanfare", Type = "CooldownViewerSound", EnumValue = 60 },
				{ Name = "War3GateOpen", Type = "CooldownViewerSound", EnumValue = 61 },
				{ Name = "War3Gold", Type = "CooldownViewerSound", EnumValue = 62 },
				{ Name = "War3MagicShimmer", Type = "CooldownViewerSound", EnumValue = 63 },
				{ Name = "War3Ringout", Type = "CooldownViewerSound", EnumValue = 64 },
				{ Name = "War3Rooster", Type = "CooldownViewerSound", EnumValue = 65 },
				{ Name = "War3ShimmerBell", Type = "CooldownViewerSound", EnumValue = 66 },
				{ Name = "War3WolfHowl", Type = "CooldownViewerSound", EnumValue = 67 },
				{ Name = "ShortBellStrike", Type = "CooldownViewerSound", EnumValue = 68 },
				{ Name = "ShortBellTree", Type = "CooldownViewerSound", EnumValue = 69 },
				{ Name = "ShortBigPot", Type = "CooldownViewerSound", EnumValue = 70 },
				{ Name = "ShortBlades", Type = "CooldownViewerSound", EnumValue = 71 },
				{ Name = "ShortCoffeeMug", Type = "CooldownViewerSound", EnumValue = 72 },
				{ Name = "ShortCowBell", Type = "CooldownViewerSound", EnumValue = 73 },
				{ Name = "ShortFingerSnap", Type = "CooldownViewerSound", EnumValue = 74 },
				{ Name = "ShortGuitar", Type = "CooldownViewerSound", EnumValue = 75 },
				{ Name = "ShortKalimba", Type = "CooldownViewerSound", EnumValue = 76 },
				{ Name = "ShortMetalBladeDrop", Type = "CooldownViewerSound", EnumValue = 77 },
				{ Name = "ShortMetalBladeOnRod", Type = "CooldownViewerSound", EnumValue = 78 },
				{ Name = "ShortMetalImpact", Type = "CooldownViewerSound", EnumValue = 79 },
				{ Name = "ShortMiniWoodXylophone", Type = "CooldownViewerSound", EnumValue = 80 },
				{ Name = "ShortPaperCup", Type = "CooldownViewerSound", EnumValue = 81 },
				{ Name = "ShortSheetMetal", Type = "CooldownViewerSound", EnumValue = 82 },
				{ Name = "ShortStovePipe", Type = "CooldownViewerSound", EnumValue = 83 },
				{ Name = "ShortStovePipeBlade", Type = "CooldownViewerSound", EnumValue = 84 },
				{ Name = "ShortSwordShing", Type = "CooldownViewerSound", EnumValue = 85 },
				{ Name = "ShortSynthBleep", Type = "CooldownViewerSound", EnumValue = 86 },
				{ Name = "ShortSynthBlurp", Type = "CooldownViewerSound", EnumValue = 87 },
				{ Name = "ShortSynthError", Type = "CooldownViewerSound", EnumValue = 88 },
				{ Name = "ShortSynthHigh", Type = "CooldownViewerSound", EnumValue = 89 },
				{ Name = "ShortTriangle", Type = "CooldownViewerSound", EnumValue = 90 },
				{ Name = "ShortWaterDrop", Type = "CooldownViewerSound", EnumValue = 91 },
				{ Name = "ShortWineBottle", Type = "CooldownViewerSound", EnumValue = 92 },
				{ Name = "ShortWoodXylophone", Type = "CooldownViewerSound", EnumValue = 93 },
			},
		},
		{
			Name = "GroupBuffItemFlags",
			Type = "Enumeration",
			NumValues = 1,
			MinValue = 1,
			MaxValue = 1,
			Fields =
			{
				{ Name = "HideByDefault", Type = "GroupBuffItemFlags", EnumValue = 1 },
			},
		},
		{
			Name = "CooldownViewerUIConstants",
			Type = "Constants",
			Values =
			{
				{ Name = "COOLDOWN_VIEWER_LINKED_SPELLS_SIZE", Type = "number", Value = 4 },
				{ Name = "COOLDOWN_VIEWER_CATEGORY_SET_SIZE", Type = "number", Value = 16 },
				{ Name = "COOLDOWN_VIEWER_SPEC_AGNOSTIC_PARENT_ID", Type = "number", Value = 0 },
				{ Name = "COOLDOWN_VIEWER_COMBAT_POTION_ICON_FID", Type = "number", Value = 134737 },
				{ Name = "COOLDOWN_VIEWER_HEALTH_POTION_ICON_FID", Type = "number", Value = 134834 },
				{ Name = "COOLDOWN_VIEWER_HEALTHSTONE_ICON_FID", Type = "number", Value = 538745 },
			},
		},
		{
			Name = "GroupBuffUIConstants",
			Type = "Constants",
			Values =
			{
				{ Name = "GROUP_BUFF_ITEM_LIST_SIZE", Type = "number", Value = 16 },
			},
		},
	},
	Predicates =
	{
	},
};

APIDocumentation:AddDocumentationTable(CooldownViewerConstants);