local GuildConstants =
{
	Tables =
	{
		{
			Name = "GuildErrorType",
			Type = "Enumeration",
			NumValues = 51,
			MinValue = 0,
			MaxValue = 50,
			Fields =
			{
				{ Name = "Success", Type = "GuildErrorType", EnumValue = 0 },
				{ Name = "UnknownError", Type = "GuildErrorType", EnumValue = 1 },
				{ Name = "AlreadyInGuild", Type = "GuildErrorType", EnumValue = 2 },
				{ Name = "TargetAlreadyInGuild", Type = "GuildErrorType", EnumValue = 3 },
				{ Name = "InvitedToGuild", Type = "GuildErrorType", EnumValue = 4 },
				{ Name = "TargetInvitedToGuild", Type = "GuildErrorType", EnumValue = 5 },
				{ Name = "NameInvalid", Type = "GuildErrorType", EnumValue = 6 },
				{ Name = "NameAlreadyExists", Type = "GuildErrorType", EnumValue = 7 },
				{ Name = "NoPermisson", Type = "GuildErrorType", EnumValue = 8 },
				{ Name = "NotInGuild", Type = "GuildErrorType", EnumValue = 9 },
				{ Name = "TargetNotInGuild", Type = "GuildErrorType", EnumValue = 10 },
				{ Name = "PlayerNotFound", Type = "GuildErrorType", EnumValue = 11 },
				{ Name = "WrongFaction", Type = "GuildErrorType", EnumValue = 12 },
				{ Name = "TargetTooHigh", Type = "GuildErrorType", EnumValue = 13 },
				{ Name = "TargetTooLow", Type = "GuildErrorType", EnumValue = 14 },
				{ Name = "TooManyRanks", Type = "GuildErrorType", EnumValue = 15 },
				{ Name = "TooFewRanks", Type = "GuildErrorType", EnumValue = 16 },
				{ Name = "RanksLocked", Type = "GuildErrorType", EnumValue = 17 },
				{ Name = "RankInUse", Type = "GuildErrorType", EnumValue = 18 },
				{ Name = "Ignored", Type = "GuildErrorType", EnumValue = 19 },
				{ Name = "Busy", Type = "GuildErrorType", EnumValue = 20 },
				{ Name = "TargetLevelTooLow", Type = "GuildErrorType", EnumValue = 21 },
				{ Name = "TargetLevelTooHigh", Type = "GuildErrorType", EnumValue = 22 },
				{ Name = "TooManyMembers", Type = "GuildErrorType", EnumValue = 23 },
				{ Name = "InvalidBankTab", Type = "GuildErrorType", EnumValue = 24 },
				{ Name = "WithdrawLimit", Type = "GuildErrorType", EnumValue = 25 },
				{ Name = "NotEnoughMoney", Type = "GuildErrorType", EnumValue = 26 },
				{ Name = "TeamNotFound", Type = "GuildErrorType", EnumValue = 27 },
				{ Name = "BankTabFull", Type = "GuildErrorType", EnumValue = 28 },
				{ Name = "BadItem", Type = "GuildErrorType", EnumValue = 29 },
				{ Name = "TeamsLocked", Type = "GuildErrorType", EnumValue = 30 },
				{ Name = "TooMuchMoney", Type = "GuildErrorType", EnumValue = 31 },
				{ Name = "WrongBankTab", Type = "GuildErrorType", EnumValue = 32 },
				{ Name = "TooManyCreate", Type = "GuildErrorType", EnumValue = 33 },
				{ Name = "RankRequiresAuthenticator", Type = "GuildErrorType", EnumValue = 34 },
				{ Name = "BankTabLocked", Type = "GuildErrorType", EnumValue = 35 },
				{ Name = "TrialAccount", Type = "GuildErrorType", EnumValue = 36 },
				{ Name = "VeteranAccount", Type = "GuildErrorType", EnumValue = 37 },
				{ Name = "UndeletableDueToLevel", Type = "GuildErrorType", EnumValue = 38 },
				{ Name = "LockedForMove", Type = "GuildErrorType", EnumValue = 39 },
				{ Name = "GuildRepTooLow", Type = "GuildErrorType", EnumValue = 40 },
				{ Name = "CantInviteSelf", Type = "GuildErrorType", EnumValue = 41 },
				{ Name = "HasRestriction", Type = "GuildErrorType", EnumValue = 42 },
				{ Name = "BankNotFound", Type = "GuildErrorType", EnumValue = 43 },
				{ Name = "NewLeaderWrongFaction", Type = "GuildErrorType", EnumValue = 44 },
				{ Name = "GuildBankNotAvailable", Type = "GuildErrorType", EnumValue = 45 },
				{ Name = "NewLeaderWrongRealm", Type = "GuildErrorType", EnumValue = 46 },
				{ Name = "DeleteNoAppropriateLeader", Type = "GuildErrorType", EnumValue = 47 },
				{ Name = "RealmMismatch", Type = "GuildErrorType", EnumValue = 48 },
				{ Name = "InCooldown", Type = "GuildErrorType", EnumValue = 49 },
				{ Name = "ReservationExpired", Type = "GuildErrorType", EnumValue = 50 },
			},
		},
	},
};

APIDocumentation:AddDocumentationTable(GuildConstants);