local PlayerHousingConstants =
{
	Tables =
	{
		{
			Name = "HouseEditingContext",
			Type = "Enumeration",
			NumValues = 4,
			MinValue = 0,
			MaxValue = 3,
			Fields =
			{
				{ Name = "None", Type = "HouseEditingContext", EnumValue = 0 },
				{ Name = "Decor", Type = "HouseEditingContext", EnumValue = 1 },
				{ Name = "Room", Type = "HouseEditingContext", EnumValue = 2 },
				{ Name = "Fixture", Type = "HouseEditingContext", EnumValue = 3 },
			},
		},
		{
			Name = "HouseEditorMode",
			Type = "Enumeration",
			NumValues = 7,
			MinValue = 0,
			MaxValue = 6,
			Fields =
			{
				{ Name = "None", Type = "HouseEditorMode", EnumValue = 0 },
				{ Name = "BasicDecor", Type = "HouseEditorMode", EnumValue = 1 },
				{ Name = "ExpertDecor", Type = "HouseEditorMode", EnumValue = 2 },
				{ Name = "Layout", Type = "HouseEditorMode", EnumValue = 3 },
				{ Name = "Customize", Type = "HouseEditorMode", EnumValue = 4 },
				{ Name = "Cleanup", Type = "HouseEditorMode", EnumValue = 5 },
				{ Name = "ExteriorCustomization", Type = "HouseEditorMode", EnumValue = 6 },
			},
		},
		{
			Name = "HouseFinderSuggestionReason",
			Type = "Enumeration",
			NumValues = 7,
			MinValue = 0,
			MaxValue = 32,
			Fields =
			{
				{ Name = "None", Type = "HouseFinderSuggestionReason", EnumValue = 0 },
				{ Name = "Owner", Type = "HouseFinderSuggestionReason", EnumValue = 1 },
				{ Name = "CharterInvite", Type = "HouseFinderSuggestionReason", EnumValue = 2 },
				{ Name = "Guild", Type = "HouseFinderSuggestionReason", EnumValue = 4 },
				{ Name = "BNetFriends", Type = "HouseFinderSuggestionReason", EnumValue = 8 },
				{ Name = "PartySync", Type = "HouseFinderSuggestionReason", EnumValue = 16 },
				{ Name = "Random", Type = "HouseFinderSuggestionReason", EnumValue = 32 },
			},
		},
		{
			Name = "HouseOwnerError",
			Type = "Enumeration",
			NumValues = 4,
			MinValue = 0,
			MaxValue = 3,
			Fields =
			{
				{ Name = "None", Type = "HouseOwnerError", EnumValue = 0 },
				{ Name = "Faction", Type = "HouseOwnerError", EnumValue = 1 },
				{ Name = "Guild", Type = "HouseOwnerError", EnumValue = 2 },
				{ Name = "GenericPermission", Type = "HouseOwnerError", EnumValue = 3 },
			},
		},
		{
			Name = "HousingDecorFlags",
			Type = "Enumeration",
			NumValues = 10,
			MinValue = 0,
			MaxValue = 256,
			Fields =
			{
				{ Name = "None", Type = "HousingDecorFlags", EnumValue = 0 },
				{ Name = "Exterior", Type = "HousingDecorFlags", EnumValue = 1 },
				{ Name = "Interior", Type = "HousingDecorFlags", EnumValue = 2 },
				{ Name = "Unlimited", Type = "HousingDecorFlags", EnumValue = 4 },
				{ Name = "NonRemovable", Type = "HousingDecorFlags", EnumValue = 8 },
				{ Name = "AllowOnPedestal", Type = "HousingDecorFlags", EnumValue = 16 },
				{ Name = "CreateAsGameObjectProxy", Type = "HousingDecorFlags", EnumValue = 32 },
				{ Name = "Deprecated", Type = "HousingDecorFlags", EnumValue = 64 },
				{ Name = "HiddenInCatalog", Type = "HousingDecorFlags", EnumValue = 128 },
				{ Name = "PreventRemovalFromHouseChest", Type = "HousingDecorFlags", EnumValue = 256 },
			},
		},
		{
			Name = "HousingDecorPlacementRestriction",
			Type = "Enumeration",
			NumValues = 3,
			MinValue = 1,
			MaxValue = 4,
			Fields =
			{
				{ Name = "NotInsideRoom", Type = "HousingDecorPlacementRestriction", EnumValue = 1 },
				{ Name = "InvalidTarget", Type = "HousingDecorPlacementRestriction", EnumValue = 2 },
				{ Name = "InvalidCollision", Type = "HousingDecorPlacementRestriction", EnumValue = 4 },
			},
		},
		{
			Name = "HousingDecorTheme",
			Type = "Enumeration",
			NumValues = 6,
			MinValue = 0,
			MaxValue = 5,
			Fields =
			{
				{ Name = "None", Type = "HousingDecorTheme", EnumValue = 0 },
				{ Name = "Folk", Type = "HousingDecorTheme", EnumValue = 1 },
				{ Name = "Rugged", Type = "HousingDecorTheme", EnumValue = 2 },
				{ Name = "Generic", Type = "HousingDecorTheme", EnumValue = 3 },
				{ Name = "NightElf", Type = "HousingDecorTheme", EnumValue = 4 },
				{ Name = "BloodElf", Type = "HousingDecorTheme", EnumValue = 5 },
			},
		},
		{
			Name = "HousingDeleteReason",
			Type = "Enumeration",
			NumValues = 5,
			MinValue = 0,
			MaxValue = 4,
			Fields =
			{
				{ Name = "None", Type = "HousingDeleteReason", EnumValue = 0 },
				{ Name = "Cheat", Type = "HousingDeleteReason", EnumValue = 1 },
				{ Name = "CustomerService", Type = "HousingDeleteReason", EnumValue = 2 },
				{ Name = "Relinquished", Type = "HousingDeleteReason", EnumValue = 3 },
				{ Name = "Evicted", Type = "HousingDeleteReason", EnumValue = 4 },
			},
		},
		{
			Name = "HousingFixtureFlags",
			Type = "Enumeration",
			NumValues = 3,
			MinValue = 0,
			MaxValue = 2,
			Fields =
			{
				{ Name = "None", Type = "HousingFixtureFlags", EnumValue = 0 },
				{ Name = "IsDefaultFixture", Type = "HousingFixtureFlags", EnumValue = 1 },
				{ Name = "UnlockedByDefault", Type = "HousingFixtureFlags", EnumValue = 2 },
			},
		},
		{
			Name = "HousingFixtureSize",
			Type = "Enumeration",
			NumValues = 5,
			MinValue = 0,
			MaxValue = 4,
			Fields =
			{
				{ Name = "None", Type = "HousingFixtureSize", EnumValue = 0 },
				{ Name = "Any", Type = "HousingFixtureSize", EnumValue = 1 },
				{ Name = "Small", Type = "HousingFixtureSize", EnumValue = 2 },
				{ Name = "Medium", Type = "HousingFixtureSize", EnumValue = 3 },
				{ Name = "Large", Type = "HousingFixtureSize", EnumValue = 4 },
			},
		},
		{
			Name = "HousingFixtureType",
			Type = "Enumeration",
			NumValues = 9,
			MinValue = 0,
			MaxValue = 16,
			Fields =
			{
				{ Name = "None", Type = "HousingFixtureType", EnumValue = 0 },
				{ Name = "Base", Type = "HousingFixtureType", EnumValue = 9 },
				{ Name = "Roof", Type = "HousingFixtureType", EnumValue = 10 },
				{ Name = "Door", Type = "HousingFixtureType", EnumValue = 11 },
				{ Name = "Window", Type = "HousingFixtureType", EnumValue = 12 },
				{ Name = "RoofDetail", Type = "HousingFixtureType", EnumValue = 13 },
				{ Name = "RoofWindow", Type = "HousingFixtureType", EnumValue = 14 },
				{ Name = "Tower", Type = "HousingFixtureType", EnumValue = 15 },
				{ Name = "Chimney", Type = "HousingFixtureType", EnumValue = 16 },
			},
		},
		{
			Name = "HousingLayoutRestriction",
			Type = "Enumeration",
			NumValues = 10,
			MinValue = 0,
			MaxValue = 9,
			Fields =
			{
				{ Name = "None", Type = "HousingLayoutRestriction", EnumValue = 0 },
				{ Name = "RoomNotFound", Type = "HousingLayoutRestriction", EnumValue = 1 },
				{ Name = "NotInsideHouse", Type = "HousingLayoutRestriction", EnumValue = 2 },
				{ Name = "NotHouseOwner", Type = "HousingLayoutRestriction", EnumValue = 3 },
				{ Name = "IsBaseRoom", Type = "HousingLayoutRestriction", EnumValue = 4 },
				{ Name = "RoomNotLeaf", Type = "HousingLayoutRestriction", EnumValue = 5 },
				{ Name = "StairwellConnection", Type = "HousingLayoutRestriction", EnumValue = 6 },
				{ Name = "LastRoom", Type = "HousingLayoutRestriction", EnumValue = 7 },
				{ Name = "UnreachableRoom", Type = "HousingLayoutRestriction", EnumValue = 8 },
				{ Name = "SingleDoor", Type = "HousingLayoutRestriction", EnumValue = 9 },
			},
		},
		{
			Name = "HousingPermission",
			Type = "Enumeration",
			NumValues = 8,
			MinValue = 1,
			MaxValue = 128,
			Fields =
			{
				{ Name = "AddDecor", Type = "HousingPermission", EnumValue = 1 },
				{ Name = "ChangeDecorParam", Type = "HousingPermission", EnumValue = 2 },
				{ Name = "EnterDecorEditMode", Type = "HousingPermission", EnumValue = 4 },
				{ Name = "MoveDecor", Type = "HousingPermission", EnumValue = 8 },
				{ Name = "RemoveDecor", Type = "HousingPermission", EnumValue = 16 },
				{ Name = "EditLayout", Type = "HousingPermission", EnumValue = 32 },
				{ Name = "EditFixtures", Type = "HousingPermission", EnumValue = 64 },
				{ Name = "EditAlterations", Type = "HousingPermission", EnumValue = 128 },
			},
		},
		{
			Name = "HousingPlacedDecorFlags",
			Type = "Enumeration",
			NumValues = 2,
			MinValue = 0,
			MaxValue = 1,
			Fields =
			{
				{ Name = "None", Type = "HousingPlacedDecorFlags", EnumValue = 0 },
				{ Name = "PrecisionRotationApplied", Type = "HousingPlacedDecorFlags", EnumValue = 1 },
			},
		},
		{
			Name = "HousingPlotOwnerType",
			Type = "Enumeration",
			NumValues = 4,
			MinValue = 0,
			MaxValue = 3,
			Fields =
			{
				{ Name = "None", Type = "HousingPlotOwnerType", EnumValue = 0 },
				{ Name = "Stranger", Type = "HousingPlotOwnerType", EnumValue = 1 },
				{ Name = "Friend", Type = "HousingPlotOwnerType", EnumValue = 2 },
				{ Name = "Self", Type = "HousingPlotOwnerType", EnumValue = 3 },
			},
		},
		{
			Name = "HousingResult",
			Type = "Enumeration",
			NumValues = 67,
			MinValue = 0,
			MaxValue = 66,
			Fields =
			{
				{ Name = "Success", Type = "HousingResult", EnumValue = 0 },
				{ Name = "CannotAfford", Type = "HousingResult", EnumValue = 1 },
				{ Name = "CharterComplete", Type = "HousingResult", EnumValue = 2 },
				{ Name = "CollisionInvalid", Type = "HousingResult", EnumValue = 3 },
				{ Name = "DbError", Type = "HousingResult", EnumValue = 4 },
				{ Name = "DecorNotFound", Type = "HousingResult", EnumValue = 5 },
				{ Name = "DuplicateCharterSignature", Type = "HousingResult", EnumValue = 6 },
				{ Name = "FilterRejected", Type = "HousingResult", EnumValue = 7 },
				{ Name = "GenericFailure", Type = "HousingResult", EnumValue = 8 },
				{ Name = "GuildNotLoaded", Type = "HousingResult", EnumValue = 9 },
				{ Name = "HouseNotFound", Type = "HousingResult", EnumValue = 10 },
				{ Name = "IncorrectFaction", Type = "HousingResult", EnumValue = 11 },
				{ Name = "InvalidDecorItem", Type = "HousingResult", EnumValue = 12 },
				{ Name = "InvalidGuild", Type = "HousingResult", EnumValue = 13 },
				{ Name = "InvalidInteraction", Type = "HousingResult", EnumValue = 14 },
				{ Name = "InvalidNeighborhoodName", Type = "HousingResult", EnumValue = 15 },
				{ Name = "InvalidRoomLayout", Type = "HousingResult", EnumValue = 16 },
				{ Name = "LockedByOtherPlayer", Type = "HousingResult", EnumValue = 17 },
				{ Name = "LockOperationFailed", Type = "HousingResult", EnumValue = 18 },
				{ Name = "MaxDecorReached", Type = "HousingResult", EnumValue = 19 },
				{ Name = "MoreHouseSlotsNeeded", Type = "HousingResult", EnumValue = 20 },
				{ Name = "MoreSignaturesNeeded", Type = "HousingResult", EnumValue = 21 },
				{ Name = "NeighborhoodNotFound", Type = "HousingResult", EnumValue = 22 },
				{ Name = "NotInDecorEditMode", Type = "HousingResult", EnumValue = 23 },
				{ Name = "NotInLayoutEditMode", Type = "HousingResult", EnumValue = 24 },
				{ Name = "NotInsideHouse", Type = "HousingResult", EnumValue = 25 },
				{ Name = "NotOnOwnedPlot", Type = "HousingResult", EnumValue = 26 },
				{ Name = "OperationAborted", Type = "HousingResult", EnumValue = 27 },
				{ Name = "PermissionDenied", Type = "HousingResult", EnumValue = 28 },
				{ Name = "PlacementTargetInvalid", Type = "HousingResult", EnumValue = 29 },
				{ Name = "PlotNotFound", Type = "HousingResult", EnumValue = 30 },
				{ Name = "PlotReserved", Type = "HousingResult", EnumValue = 31 },
				{ Name = "RoomNotFound", Type = "HousingResult", EnumValue = 32 },
				{ Name = "RoomUpdateFailed", Type = "HousingResult", EnumValue = 33 },
				{ Name = "RpcFailure", Type = "HousingResult", EnumValue = 34 },
				{ Name = "ServiceNotAvailable", Type = "HousingResult", EnumValue = 35 },
				{ Name = "TimeoutLimit", Type = "HousingResult", EnumValue = 36 },
				{ Name = "TokenRequired", Type = "HousingResult", EnumValue = 37 },
				{ Name = "TransactionFailure", Type = "HousingResult", EnumValue = 38 },
				{ Name = "UnlockOperationFailed", Type = "HousingResult", EnumValue = 39 },
				{ Name = "NotInFixtureEditMode", Type = "HousingResult", EnumValue = 40 },
				{ Name = "FixtureSizeMismatch", Type = "HousingResult", EnumValue = 41 },
				{ Name = "FixtureTypeMismatch", Type = "HousingResult", EnumValue = 42 },
				{ Name = "MissingCoreFixture", Type = "HousingResult", EnumValue = 43 },
				{ Name = "PlotNotVacant", Type = "HousingResult", EnumValue = 44 },
				{ Name = "PlotReservationCooldown", Type = "HousingResult", EnumValue = 45 },
				{ Name = "HookNotChildOfFixture", Type = "HousingResult", EnumValue = 46 },
				{ Name = "FixtureHouseTypeMismatch", Type = "HousingResult", EnumValue = 47 },
				{ Name = "FixtureHookEmpty", Type = "HousingResult", EnumValue = 48 },
				{ Name = "FixtureHookOccupied", Type = "HousingResult", EnumValue = 49 },
				{ Name = "FixtureCantDeleteDoor", Type = "HousingResult", EnumValue = 50 },
				{ Name = "FixtureNotFound", Type = "HousingResult", EnumValue = 51 },
				{ Name = "DecorNotFoundInStorage", Type = "HousingResult", EnumValue = 52 },
				{ Name = "MissingPrivateNeighborhoodInvite", Type = "HousingResult", EnumValue = 53 },
				{ Name = "MissingExpansionAccess", Type = "HousingResult", EnumValue = 54 },
				{ Name = "MissingDye", Type = "HousingResult", EnumValue = 55 },
				{ Name = "MissingFactionMap", Type = "HousingResult", EnumValue = 56 },
				{ Name = "InvalidMap", Type = "HousingResult", EnumValue = 57 },
				{ Name = "InvalidHouse", Type = "HousingResult", EnumValue = 58 },
				{ Name = "InvalidInstance", Type = "HousingResult", EnumValue = 59 },
				{ Name = "PlayerNotInInstance", Type = "HousingResult", EnumValue = 60 },
				{ Name = "FixtureNotOwned", Type = "HousingResult", EnumValue = 61 },
				{ Name = "DecorItemNotDestroyable", Type = "HousingResult", EnumValue = 62 },
				{ Name = "HouseExteriorRootNotFound", Type = "HousingResult", EnumValue = 63 },
				{ Name = "DecorCannotBeRedeemed", Type = "HousingResult", EnumValue = 64 },
				{ Name = "TimerunningNotAllowed", Type = "HousingResult", EnumValue = 65 },
				{ Name = "TooManyRequests", Type = "HousingResult", EnumValue = 66 },
			},
		},
		{
			Name = "HousingRoomComponentCeilingType",
			Type = "Enumeration",
			NumValues = 2,
			MinValue = 0,
			MaxValue = 1,
			Fields =
			{
				{ Name = "Flat", Type = "HousingRoomComponentCeilingType", EnumValue = 0 },
				{ Name = "Vaulted", Type = "HousingRoomComponentCeilingType", EnumValue = 1 },
			},
		},
		{
			Name = "HousingRoomComponentDoorType",
			Type = "Enumeration",
			NumValues = 3,
			MinValue = 0,
			MaxValue = 2,
			Fields =
			{
				{ Name = "None", Type = "HousingRoomComponentDoorType", EnumValue = 0 },
				{ Name = "Doorway", Type = "HousingRoomComponentDoorType", EnumValue = 1 },
				{ Name = "Threshold", Type = "HousingRoomComponentDoorType", EnumValue = 2 },
			},
		},
		{
			Name = "HousingRoomComponentFloorType",
			Type = "Enumeration",
			NumValues = 1,
			MinValue = 0,
			MaxValue = 0,
			Fields =
			{
				{ Name = "Floor", Type = "HousingRoomComponentFloorType", EnumValue = 0 },
			},
		},
		{
			Name = "HousingRoomComponentOptionFlags",
			Type = "Enumeration",
			NumValues = 2,
			MinValue = 0,
			MaxValue = 1,
			Fields =
			{
				{ Name = "None", Type = "HousingRoomComponentOptionFlags", EnumValue = 0 },
				{ Name = "IsDefault", Type = "HousingRoomComponentOptionFlags", EnumValue = 1 },
			},
		},
		{
			Name = "HousingRoomComponentOptionType",
			Type = "Enumeration",
			NumValues = 3,
			MinValue = 0,
			MaxValue = 2,
			Fields =
			{
				{ Name = "Cosmetic", Type = "HousingRoomComponentOptionType", EnumValue = 0 },
				{ Name = "DoorwayWall", Type = "HousingRoomComponentOptionType", EnumValue = 1 },
				{ Name = "Doorway", Type = "HousingRoomComponentOptionType", EnumValue = 2 },
			},
		},
		{
			Name = "HousingRoomComponentStairType",
			Type = "Enumeration",
			NumValues = 5,
			MinValue = 0,
			MaxValue = 4,
			Fields =
			{
				{ Name = "None", Type = "HousingRoomComponentStairType", EnumValue = 0 },
				{ Name = "StartToEnd", Type = "HousingRoomComponentStairType", EnumValue = 1 },
				{ Name = "StartToMiddle", Type = "HousingRoomComponentStairType", EnumValue = 2 },
				{ Name = "MiddleToMiddle", Type = "HousingRoomComponentStairType", EnumValue = 3 },
				{ Name = "MiddleToEnd", Type = "HousingRoomComponentStairType", EnumValue = 4 },
			},
		},
		{
			Name = "HousingRoomComponentTextureFlags",
			Type = "Enumeration",
			NumValues = 2,
			MinValue = 0,
			MaxValue = 1,
			Fields =
			{
				{ Name = "None", Type = "HousingRoomComponentTextureFlags", EnumValue = 0 },
				{ Name = "UnlockedByDefault", Type = "HousingRoomComponentTextureFlags", EnumValue = 1 },
			},
		},
		{
			Name = "HousingRoomComponentType",
			Type = "Enumeration",
			NumValues = 7,
			MinValue = 0,
			MaxValue = 6,
			Fields =
			{
				{ Name = "None", Type = "HousingRoomComponentType", EnumValue = 0 },
				{ Name = "Wall", Type = "HousingRoomComponentType", EnumValue = 1 },
				{ Name = "Floor", Type = "HousingRoomComponentType", EnumValue = 2 },
				{ Name = "Ceiling", Type = "HousingRoomComponentType", EnumValue = 3 },
				{ Name = "Stairs", Type = "HousingRoomComponentType", EnumValue = 4 },
				{ Name = "Pillar", Type = "HousingRoomComponentType", EnumValue = 5 },
				{ Name = "Doorway", Type = "HousingRoomComponentType", EnumValue = 6 },
			},
		},
		{
			Name = "HousingRoomFlags",
			Type = "Enumeration",
			NumValues = 5,
			MinValue = 0,
			MaxValue = 8,
			Fields =
			{
				{ Name = "None", Type = "HousingRoomFlags", EnumValue = 0 },
				{ Name = "BaseRoom", Type = "HousingRoomFlags", EnumValue = 1 },
				{ Name = "HasStairs", Type = "HousingRoomFlags", EnumValue = 2 },
				{ Name = "UnlockedByDefault", Type = "HousingRoomFlags", EnumValue = 4 },
				{ Name = "HasCustomGeometry", Type = "HousingRoomFlags", EnumValue = 8 },
			},
		},
		{
			Name = "HousingStorageDecorFlags",
			Type = "Enumeration",
			NumValues = 3,
			MinValue = 0,
			MaxValue = 2,
			Fields =
			{
				{ Name = "None", Type = "HousingStorageDecorFlags", EnumValue = 0 },
				{ Name = "Licensed", Type = "HousingStorageDecorFlags", EnumValue = 1 },
				{ Name = "Revoke", Type = "HousingStorageDecorFlags", EnumValue = 2 },
			},
		},
		{
			Name = "HousingThemeFlags",
			Type = "Enumeration",
			NumValues = 2,
			MinValue = 0,
			MaxValue = 1,
			Fields =
			{
				{ Name = "None", Type = "HousingThemeFlags", EnumValue = 0 },
				{ Name = "UnlockedByDefault", Type = "HousingThemeFlags", EnumValue = 1 },
			},
		},
		{
			Name = "NeighbordhoodInitiativeCategory",
			Type = "Enumeration",
			NumValues = 2,
			MinValue = 0,
			MaxValue = 1,
			Fields =
			{
				{ Name = "Current", Type = "NeighbordhoodInitiativeCategory", EnumValue = 0 },
				{ Name = "Legacy", Type = "NeighbordhoodInitiativeCategory", EnumValue = 1 },
			},
		},
		{
			Name = "NeighborhoodFlags",
			Type = "Enumeration",
			NumValues = 3,
			MinValue = 0,
			MaxValue = 2,
			Fields =
			{
				{ Name = "None", Type = "NeighborhoodFlags", EnumValue = 0 },
				{ Name = "PoolParent", Type = "NeighborhoodFlags", EnumValue = 1 },
				{ Name = "OpenToPublic", Type = "NeighborhoodFlags", EnumValue = 2 },
			},
		},
		{
			Name = "NeighborhoodInviteResult",
			Type = "Enumeration",
			NumValues = 11,
			MinValue = 0,
			MaxValue = 10,
			Fields =
			{
				{ Name = "Success", Type = "NeighborhoodInviteResult", EnumValue = 0 },
				{ Name = "DbError", Type = "NeighborhoodInviteResult", EnumValue = 1 },
				{ Name = "RpcFailure", Type = "NeighborhoodInviteResult", EnumValue = 2 },
				{ Name = "GenericFailure", Type = "NeighborhoodInviteResult", EnumValue = 3 },
				{ Name = "Permission", Type = "NeighborhoodInviteResult", EnumValue = 4 },
				{ Name = "Faction", Type = "NeighborhoodInviteResult", EnumValue = 5 },
				{ Name = "PendingInvitation", Type = "NeighborhoodInviteResult", EnumValue = 6 },
				{ Name = "InviteLimit", Type = "NeighborhoodInviteResult", EnumValue = 7 },
				{ Name = "NotEnoughPlots", Type = "NeighborhoodInviteResult", EnumValue = 8 },
				{ Name = "NotFound", Type = "NeighborhoodInviteResult", EnumValue = 9 },
				{ Name = "TooManyRequests", Type = "NeighborhoodInviteResult", EnumValue = 10 },
			},
		},
		{
			Name = "NeighborhoodMapFlags",
			Type = "Enumeration",
			NumValues = 4,
			MinValue = 0,
			MaxValue = 4,
			Fields =
			{
				{ Name = "None", Type = "NeighborhoodMapFlags", EnumValue = 0 },
				{ Name = "AlliancePurchasable", Type = "NeighborhoodMapFlags", EnumValue = 1 },
				{ Name = "HordePurchasable", Type = "NeighborhoodMapFlags", EnumValue = 2 },
				{ Name = "CanSystemGenerate", Type = "NeighborhoodMapFlags", EnumValue = 4 },
			},
		},
		{
			Name = "RoomConnectionType",
			Type = "Enumeration",
			NumValues = 2,
			MinValue = 0,
			MaxValue = 1,
			Fields =
			{
				{ Name = "None", Type = "RoomConnectionType", EnumValue = 0 },
				{ Name = "All", Type = "RoomConnectionType", EnumValue = 1 },
			},
		},
	},
};

APIDocumentation:AddDocumentationTable(PlayerHousingConstants);