local WowCSConstants =
{
	Tables =
	{
		{
			Name = "FragmentID",
			Type = "Enumeration",
			NumValues = 72,
			MinValue = 0,
			MaxValue = 255,
			Fields =
			{
				{ Name = "MirrorState", Type = "FragmentID", EnumValue = 0 },
				{ Name = "EntityPosition", Type = "FragmentID", EnumValue = 1 },
				{ Name = "CgObject", Type = "FragmentID", EnumValue = 2 },
				{ Name = "JamDispatcher", Type = "FragmentID", EnumValue = 3 },
				{ Name = "HeartbeatData", Type = "FragmentID", EnumValue = 4 },
				{ Name = "FTransportLink", Type = "FragmentID", EnumValue = 5 },
				{ Name = "ClientObservablesData", Type = "FragmentID", EnumValue = 6 },
				{ Name = "TimerQueues", Type = "FragmentID", EnumValue = 7 },
				{ Name = "TransferSuspensionData", Type = "FragmentID", EnumValue = 8 },
				{ Name = "DeferredMessages", Type = "FragmentID", EnumValue = 9 },
				{ Name = "FPersistableJamServers", Type = "FragmentID", EnumValue = 10 },
				{ Name = "FPlayerJamServers", Type = "FragmentID", EnumValue = 11 },
				{ Name = "FLootObjectList", Type = "FragmentID", EnumValue = 12 },
				{ Name = "FPlayerOwnershipLink", Type = "FragmentID", EnumValue = 13 },
				{ Name = "FUnitAreaTriggerLink", Type = "FragmentID", EnumValue = 14 },
				{ Name = "Actor", Type = "FragmentID", EnumValue = 15 },
				{ Name = "FPhaseShiftData", Type = "FragmentID", EnumValue = 16 },
				{ Name = "FVendor", Type = "FragmentID", EnumValue = 17 },
				{ Name = "MirroredObjectC", Type = "FragmentID", EnumValue = 18 },
				{ Name = "FMeshObjectData", Type = "FragmentID", EnumValue = 19 },
				{ Name = "FHousingDecor", Type = "FragmentID", EnumValue = 20 },
				{ Name = "FHousingRoom", Type = "FragmentID", EnumValue = 21 },
				{ Name = "FHousingRoomComponentMesh", Type = "FragmentID", EnumValue = 22 },
				{ Name = "FHousingPlayerHouse", Type = "FragmentID", EnumValue = 23 },
				{ Name = "FHousingHouseDecorSet", Type = "FragmentID", EnumValue = 24 },
				{ Name = "FHousingHouseRoomSet", Type = "FragmentID", EnumValue = 25 },
				{ Name = "FHousingDecorProxy", Type = "FragmentID", EnumValue = 26 },
				{ Name = "FJamHousingCornerstone", Type = "FragmentID", EnumValue = 27 },
				{ Name = "FHousingDecorActor", Type = "FragmentID", EnumValue = 28 },
				{ Name = "FHousingPlotAreaTrigger", Type = "FragmentID", EnumValue = 29 },
				{ Name = "FNeighborhoodMirrorData", Type = "FragmentID", EnumValue = 30 },
				{ Name = "FMirroredPositionData", Type = "FragmentID", EnumValue = 31 },
				{ Name = "FPlayerHouseInfo", Type = "FragmentID", EnumValue = 32 },
				{ Name = "FHousingStorageMirrorData", Type = "FragmentID", EnumValue = 33 },
				{ Name = "FHousingFixture", Type = "FragmentID", EnumValue = 34 },
				{ Name = "FHousingHouseFixtureSet", Type = "FragmentID", EnumValue = 35 },
				{ Name = "Timer", Type = "FragmentID", EnumValue = 36 },
				{ Name = "FPlayerInitiativeInfo", Type = "FragmentID", EnumValue = 37 },
				{ Name = "FNeighborhoodStateData", Type = "FragmentID", EnumValue = 38 },
				{ Name = "FUnitAIGroupLink", Type = "FragmentID", EnumValue = 39 },
				{ Name = "TagItem", Type = "FragmentID", EnumValue = 200 },
				{ Name = "TagContainer", Type = "FragmentID", EnumValue = 201 },
				{ Name = "TagAzeriteEmpoweredItem", Type = "FragmentID", EnumValue = 202 },
				{ Name = "TagAzeriteItem", Type = "FragmentID", EnumValue = 203 },
				{ Name = "TagUnit", Type = "FragmentID", EnumValue = 204 },
				{ Name = "TagPlayer", Type = "FragmentID", EnumValue = 205 },
				{ Name = "TagGameObject", Type = "FragmentID", EnumValue = 206 },
				{ Name = "TagDynamicObject", Type = "FragmentID", EnumValue = 207 },
				{ Name = "TagCorpse", Type = "FragmentID", EnumValue = 208 },
				{ Name = "TagAreaTrigger", Type = "FragmentID", EnumValue = 209 },
				{ Name = "TagSceneObject", Type = "FragmentID", EnumValue = 210 },
				{ Name = "TagConversation", Type = "FragmentID", EnumValue = 211 },
				{ Name = "TagAIGroup", Type = "FragmentID", EnumValue = 212 },
				{ Name = "TagScenario", Type = "FragmentID", EnumValue = 213 },
				{ Name = "TagLootObject", Type = "FragmentID", EnumValue = 214 },
				{ Name = "TagActivePlayer", Type = "FragmentID", EnumValue = 215 },
				{ Name = "TagActiveClientS", Type = "FragmentID", EnumValue = 216 },
				{ Name = "TagActiveObjectC", Type = "FragmentID", EnumValue = 217 },
				{ Name = "TagVisibleObjectC", Type = "FragmentID", EnumValue = 218 },
				{ Name = "TagUnitVehicle", Type = "FragmentID", EnumValue = 219 },
				{ Name = "TagHousingRoom", Type = "FragmentID", EnumValue = 220 },
				{ Name = "TagMeshObject", Type = "FragmentID", EnumValue = 221 },
				{ Name = "TagHousingSubdivisionObject", Type = "FragmentID", EnumValue = 222 },
				{ Name = "TagHousingPoolObject", Type = "FragmentID", EnumValue = 223 },
				{ Name = "TagHouseExteriorPiece", Type = "FragmentID", EnumValue = 224 },
				{ Name = "TagHouseExteriorRoot", Type = "FragmentID", EnumValue = 225 },
				{ Name = "TestFragment_1", Type = "FragmentID", EnumValue = 250 },
				{ Name = "TestFragment_2", Type = "FragmentID", EnumValue = 251 },
				{ Name = "TestFragment_3", Type = "FragmentID", EnumValue = 252 },
				{ Name = "TestFragment_4", Type = "FragmentID", EnumValue = 253 },
				{ Name = "TestFragment_5", Type = "FragmentID", EnumValue = 254 },
				{ Name = "ReservedArchetypeSeparator", Type = "FragmentID", EnumValue = 255 },
			},
		},
	},
};

APIDocumentation:AddDocumentationTable(WowCSConstants);