-- Limits can be overwritten in another addon.
COMMENTATOR_MAX_OFFENSIVE_SPELLS = COMMENTATOR_MAX_OFFENSIVE_SPELLS or 5;
COMMENTATOR_MAX_DEFENSIVE_SPELLS = COMMENTATOR_MAX_DEFENSIVE_SPELLS or 5;
COMMENTATOR_MAX_DEBUFF_SPELLS = COMMENTATOR_MAX_DEBUFF_SPELLS or 2;

COMMENTATOR_INVERSE_SCALE = 768/1080;