-- Custom Gameplay category order. Set the beginning of each respective file's Register function
CUSTOM_GAMEPLAY_SETTINGS_ORDER = {
	[CONTROLS_LABEL] = 7,
	[INTERFACE_LABEL] = 8,
	[ACTIONBARS_LABEL] = 9,
	[COMBAT_LABEL] = 10,
	[SOCIAL_LABEL] = 11,
	[GAMEPAD_LABEL] = 12,
	[PING_SYSTEM_LABEL] = 13,
	[SETTINGS_KEYBINDINGS_LABEL] = 14,
	[ADVANCED_OPTIONS_LABEL] = 15,
	[NAMEPLATE_OPTIONS_LABEL] = 16
};