KIOSK_SPLASH_END_BODY1_TEXT = "Thank you for playing!";
KIOSK_SPLASH_END_BACKGROUND = "Interface/CharacterSelection/Kiosk-Mode-End-background-c60";
KIOSK_TIME_REMAINING_FORMAT = "Time Left: %s";
KIOSK_DEFAULT_TEMPLATE_SET_ID1 = 257;
KIOSK_DEFAULT_TEMPLATE_SET_ID2 = 258;
KIOSK_DEFAULT_SESSION_DURATION1 = 30 * 60;
KIOSK_DEFAULT_SESSION_DURATION2 = 45 * 60;
