VideoOptionsTooltip = GlueTooltip;
VideoOptionsDropDownMenu_Initialize = UIDropDownMenu_Initialize;
VideoOptionsDropDownMenu_GetSelectedID = UIDropDownMenu_GetSelectedID;
VideoOptionsDropDownMenu_SetSelectedID = UIDropDownMenu_SetSelectedID;
VideoOptionsDropDownMenu_SetWidth = UIDropDownMenu_SetWidth;
VideoOptionsDropDownMenu_CreateInfo = UIDropDownMenu_CreateInfo;
VideoOptionsDropDownMenu_AddButton = UIDropDownMenu_AddButton;
VideoOptionsDropDownMenu_SetSelectedValue = UIDropDownMenu_SetSelectedValue;
VideoOptionsDropDownMenu_GetSelectedValue = UIDropDownMenu_GetSelectedValue;
VideoOptionsDropDownMenu_SetText = UIDropDownMenu_SetText
VideoOptionsDropDownMenu_DisableDropDown = UIDropDownMenu_DisableDropDown;
VideoOptionsDropDownMenu_EnableDropDown = UIDropDownMenu_EnableDropDown;


