NamePlateEnemyFrameOptions.showClassificationIndicator = false;
NamePlateSetupOptions.healthTextInsideBarWhenNameAboveHealthBar = true;
NamePlateSetupOptions.nameJustificationWhenAboveHealthBar = "CENTER";
NamePlateSetupOptions.useOutlinedFontWhenAboveHealthBar = true;
