-- All values listed here can be updated from NamePlateDriverMixin:UpdateNamePlateOptions.
-- Default values are just present to show the complete list of available options.
NamePlateSetupOptions = {
	castBarBorderHeight = 16,
	castBarBorderWidth = 128,
	castBarFontHeight = 12,
	castBarHeight = 16,
	castBarShieldHeight = 12,
	castBarShieldWidth = 10,
	castBarToHealthBarSpacing = 2,
	castIconHeight = 12,
	castIconWidth = 12,
	classificationScale = 1.0,
	healthBarBorderHeight = 16,
	healthBarBorderWidth = 128,
	healthBarFontHeight = 16,
	healthBarHeight = 20,
	healthBarToNameAboveSpacing = 2,
	hideIconWhenNotInterruptible = true,
	horizontalScale = 1.0,
	insetWidth = 12,
	levelFontHeight = 10,
	levelIconHeight = 15,
	levelIconWidth = 15,
	showLevel = false,
	spellNameInsideCastBar = false,
	unitNameAnchorStyle = NamePlateConstants.NAME_ANCHOR_STYLES.InsideHealthBar,
	useClassicCastBar = false,
	useClassicHealthBar = false,
	verticalScale = 1.0,
}

-- Some values listed here can be updated from NamePlateDriverMixin:UpdateNamePlateOptions.
-- Others are just 'constants' for nameplates attached to friendly units.
NamePlateFriendlyFrameOptions = {
	colorHealthBySelection = true,
	colorHealthWithExtendedColors = true,
	colorNameBySelection = true,
	colorNameWithExtendedColors = true,
	considerSelectionInCombatAsHostile = true,
	defaultBorderColor = CreateColor(0, 0, 0, .8),
	displayAggroHighlight = false,
	displayHealPrediction = true,
	displayName = true,
	displayNameByPlayerNameRules = true,
	displayNameWhenSelected = true,
	displaySelectionHighlight = false,
	displaySelectionHighlightOnMouseover = true,
	fadeOutOfRange = false,
	greyOutWhenTapDenied = false,
	nameMouseoverColor = nil, -- nil = no highlight.
	selectedBorderColor = CreateColor(1, 1, 1, .35),
	showClassificationIndicator = false,
	showLevel = false,
	showPvPClassificationIndicator = true,
	smoothHealthUpdates = false,
	softTargetBorderColor = CreateColor(.9, 1, .9, .25),
	tankBorderColor = CreateColor(1, 1, 0, .6),
	updateNameUsesGetUnitName = true,
	useClassColors = true,
	usePlayerForAggroHighlightThreat = false,
}

-- Some values listed here can be updated from NamePlateDriverMixin:UpdateNamePlateOptions.
-- Others are just 'constants' for nameplates attached to enemy units.
NamePlateEnemyFrameOptions = {
	colorHealthBySelection = true,
	colorHealthWithExtendedColors = true,
	colorNameBySelection = true,
	colorNameWithExtendedColors = true,
	considerSelectionInCombatAsHostile = true,
	defaultBorderColor = CreateColor(0, 0, 0, 1),
	displayAggroHighlight = false,
	displayHealPrediction = true,
	displayName = true,
	displayNameByPlayerNameRules = true,
	displayNameWhenSelected = true,
	displaySelectionHighlight = false,
	displaySelectionHighlightOnMouseover = true,
	fadeOutOfRange = false,
	greyOutWhenTapDenied = true,
	nameMouseoverColor = nil, -- nil = no highlight.
	selectedBorderColor = CreateColor(1, 1, 1, .9),
	showClassificationIndicator = true,
	showLevel = false,
	showPvPClassificationIndicator = true,
	smoothHealthUpdates = false,
	softTargetBorderColor = CreateColor(1, 1, 1, .4),
	tankBorderColor = CreateColor(1, 1, 0, .6),
	updateNameUsesGetUnitName = true,
	useClassColors = true,
	usePlayerForAggroHighlightThreat = true,
}
