FONT_COLOR_CODE_CLOSE = "|r";

FACTION_BAR_COLORS = 
{
	FACTION_RED_COLOR,
	FACTION_RED_COLOR,
	FACTION_ORANGE_COLOR,
	FACTION_YELLOW_COLOR,
	FACTION_GREEN_COLOR,
	FACTION_GREEN_COLOR,
	FACTION_GREEN_COLOR,
	FACTION_GREEN_COLOR,
};

FACTION_BAR_Textures =
{
	"UI-HUD-ExperienceBar-Fill-Reputation-Faction-Red",
	"UI-HUD-ExperienceBar-Fill-Reputation-Faction-Red",
	"UI-HUD-ExperienceBar-Fill-Reputation-Faction-Orange",
	"UI-HUD-ExperienceBar-Fill-Reputation-Faction-Yellow",
	"UI-HUD-ExperienceBar-Fill-Reputation-Faction-Green",
	"UI-HUD-ExperienceBar-Fill-Reputation-Faction-Green",
	"UI-HUD-ExperienceBar-Fill-Reputation-Faction-Green",
	"UI-HUD-ExperienceBar-Fill-Reputation-Faction-Green",
};

MATERIAL_TEXT_COLOR_TABLE = 
{
	["Default"] = DEFAULT_MATERIAL_TEXT_COLOR,
	["Stone"] = STONE_MATERIAL_TEXT_COLOR,
	["Parchment"] = PARCHMENT_MATERIAL_TEXT_COLOR,
	["Marble"] = MARBLE_MATERIAL_TEXT_COLOR,
	["Silver"] = SILVER_MATERIAL_TEXT_COLOR,
	["Bronze"] = BRONZE_MATERIAL_TEXT_COLOR,
	["ParchmentLarge"] = PARCHMENTLARGE_MATERIAL_TEXT_COLOR,
	["Progenitor"] = PROGENITOR_MATERIAL_TEXT_COLOR,
};

MATERIAL_TITLETEXT_COLOR_TABLE = 
{
	["Default"] = DEFAULT_MATERIAL_TITLETEXT_COLOR,
	["Stone"] = STONE_MATERIAL_TITLETEXT_COLOR,
	["Parchment"] = PARCHMENT_MATERIAL_TITLETEXT_COLOR,
	["Marble"] = MARBLE_MATERIAL_TITLETEXT_COLOR,
	["Silver"] = SILVER_MATERIAL_TITLETEXT_COLOR,
	["Bronze"] = BRONZE_MATERIAL_TITLETEXT_COLOR,
	["ParchmentLarge"] = PARCHMENTLARGE_MATERIAL_TITLETEXT_COLOR,
	["Progenitor"] = PROGENITOR_MATERIAL_TITLETEXT_COLOR,
};

PLAYER_FACTION_COLORS = 
{ 
	[0] = PLAYER_FACTION_COLOR_HORDE, 
	[1] = PLAYER_FACTION_COLOR_ALLIANCE,
};

PLAYER_FACTION_COLORS_HEX = 
{ 
	[0] = PLAYER_FACTION_COLOR_HORDE:GenerateHexColor(), 
	[1] = PLAYER_FACTION_COLOR_ALLIANCE:GenerateHexColor(), 
};

COVENANT_COLORS = 
{ 
	[1] = KYRIAN_BLUE_COLOR,
	[2] = VENTHYR_RED_COLOR,
	[3] = NIGHT_FAE_BLUE_COLOR,
	[4] = NECROLORD_GREEN_COLOR,

	Kyrian = KYRIAN_BLUE_COLOR,
	Venthyr = VENTHYR_RED_COLOR,
	NightFae = NIGHT_FAE_BLUE_COLOR,
	Necrolord = NECROLORD_GREEN_COLOR,
}